-- 008 Seed: instrument version, 48 elements, 288 anchors
--
-- Loaded from Blend GEA_Scoring Instrument v0.6.
-- The version is created as draft. It stays draft until every seed migration has
-- run and the activation gate passes, because activating it makes all of this
-- immutable.

insert into instrument_version (id, label, runbook_label, status, notes)
values ('0f6a0006-0000-4000-8000-000000000006', 'v0.6', 'Blend GEA Runbook v0.3', 'draft',
        'Seeded from the six reference workbooks. Cap rules, analysis field requirements and interview question mapping carry the review decisions of 23 September 2026.');

insert into element (instrument_version_id, ref, kind, stage_code, from_stage, to_stage, name,
  why_assessed, evidence_required, method, owner_role, support_role, fallback_rule,
  ne_permitted, tier_dependent, evidence_decays, has_retrievability_test, sort_order) values
  ('0f6a0006-0000-4000-8000-000000000006', '1.1', 'element', '01', null, null, 'ICP definition and evidence base',
   'Everything downstream inherits the quality of this answer. A demand programme built on a vague ICP produces expensive pipeline sales will not work.', 'The current ICP document with author and date. Closed-won records for the last 24 months with firmographics. Renewal, expansion and churn cohort lists. Campaign briefs and qualification criteria currently in use.', 'Document review; CRM extract; ICP Reconciliation sheet; interview with marketing and sales leadership',
   'GC', 'GA for extracts', 'An ICP that cannot be produced on request scores 0. Absence of closed-won firmographics is a Stage 1 data-quality flag and caps this element at 2 with confidence Low.',
   true, false, false, false, 1),
  ('0f6a0006-0000-4000-8000-000000000006', '1.2', 'element', '01', null, null, 'Segment prioritisation and addressable market logic',
   'Coverage planning, headcount and channel budget are all set against a segment priority. If that order is not derived from anything, every allocation downstream is a guess.', 'Current GTM or territory plan showing segment priority. Any sizing work and its derivation. Win rate, ACV and gross retention cut by segment. Bottom-up qualifying account counts if they exist.', 'Document review; CRM extract cut by segment; interview with CRO or VP Sales and marketing leadership',
   'GA', 'GC', 'Where segment is not a recorded field, note it as a finding, reconstruct segment from firmographics for the analysis, and cap at 3 with confidence Medium.',
   true, false, false, false, 2),
  ('0f6a0006-0000-4000-8000-000000000006', '1.3', 'element', '01', null, null, 'Win/loss and churn pattern analysis',
   'Win/loss and churn are the only unbiased evidence of who the company is actually for. Most companies hold the data and never cut it.', 'Two years of closed-won and closed-lost records including loss reason. Churn and downgrade records with reason and date. Any win/loss interview output. Evidence of a review forum and its outputs.', 'CRM extract and pattern analysis; document review; interview with sales leadership and CS leadership',
   'GA', 'GC', 'Where loss reason is absent or defaulted on more than half of records, that is the finding. Score no higher than 1 and record the defaulting rate in the report.',
   true, false, false, false, 3),
  ('0f6a0006-0000-4000-8000-000000000006', '1.4', 'element', '01', null, null, 'Competitive differentiation and defensibility of claims',
   'A claim a competitor could make word-for-word does no work in a buying decision. Differentiation that buyers do not cite is a preference held internally.', 'Current differentiation or battlecard material with review date. Competitor set as named by leadership and as recorded in closed-lost records. Win reasons cited in closed-won notes or buyer interviews.', 'Substitution test on each claim; document review; CRM extract of competitor and win-reason fields; interview with sales leadership',
   'GC', 'Demand and messaging specialist', 'Score on the material and data available. Where no competitor field is recorded, note it and use closed-lost narrative fields, at confidence Medium.',
   true, false, false, false, 4),
  ('0f6a0006-0000-4000-8000-000000000006', '1.5', 'element', '01', null, null, 'Pricing and packaging fit to segment',
   'Packaging boundaries that do not match how a segment buys create friction in every deal in that segment, and the cause is never diagnosed at the deal level.', 'Current price book and discount authority policy. Realised price and discount on closed-won records for 24 months. Any margin or win-rate analysis by package. Date and rationale of the last packaging change.', 'Document review; CRM extract of realised pricing and dispersion analysis; interview with finance and sales leadership',
   'GA', 'GC', 'Where realised pricing is not recoverable from the CRM, request it from finance. If neither source holds it, that is a material finding: score no higher than 1.',
   true, false, false, false, 5),
  ('0f6a0006-0000-4000-8000-000000000006', 'H01', 'handoff', null, '01', '02', 'Evidenced ICP into messaging',
   'What must travel: the evidenced ICP, the segment priorities, and the specific reasons best-fit customers chose the company over the alternatives they actually considered. The form it must travel in: a governed record every function reads from. What breaks without it: messaging gets written from intuition rather than renewal data, and every asset built afterwards inherits the error.', 'The artefact or system through which stage 01 output reaches the people producing messaging. Retrievability test: ask the person who last wrote a major asset to show Blend what they worked from. Version count and last refresh date.', 'Retrievability test with the asset author; document and system review; interview with both sides of the join',
   'GC', 'GA where the record sits in a system', 'A handoff is assessed by asking both sides what travels. Both sides are always available, so NE does not apply.',
   false, false, true, true, 6),
  ('0f6a0006-0000-4000-8000-000000000006', '2.1', 'element', '02', null, null, 'Core narrative and positioning statement',
   'One narrative said the same way by every person and system that speaks for the company. Divergence costs credibility at the exact moments a buyer is checking.', 'The current positioning or narrative document with owner and review date. Homepage and primary solution pages. Current pitch deck. Interview accounts from at least three senior stakeholders.', 'Document review; substitution test; interview across leadership; comparison of stated narrative to live assets',
   'GC', 'Demand and messaging specialist', 'Absence of a written narrative is scoreable at 0 without further evidence, provided interviews confirm no authoritative source exists.',
   false, false, true, false, 7),
  ('0f6a0006-0000-4000-8000-000000000006', '2.2', 'element', '02', null, null, 'Persona-level messaging architecture',
   'A CFO and a CTO reading the same page should each recognise their own problem. One message diluted for everyone reaches no one, and blocking personas go unaddressed entirely.', 'Persona definitions with pains and goals. Live assets by persona. Contact roles on closed-won deals to establish the buying group that actually appears. Conversion by persona if measured.', 'Document review; live asset audit; CRM extract of contact roles on won deals; interview with marketing leadership',
   'GC', 'Demand and messaging specialist; GA for the buying-group extract', 'Where contact roles are not populated, reconstruct the buying group from engagement history or interview, note the limitation, and cap at 3.',
   true, false, true, false, 8),
  ('0f6a0006-0000-4000-8000-000000000006', '2.3', 'element', '02', null, null, 'Proof architecture — case studies, data points, references',
   'Nearly every B2B business has more satisfied customers than usable proof. Proof coverage that does not match current segment priority is a library for a company that no longer exists.', 'All current case studies with date and whether outcomes are quantified and client-verified. Reference inventory by segment. Proof or claims library if one exists. Named production cadence and owner.', 'Document review and coverage mapping against the segment priority from 1.2; interview with marketing and CS leadership',
   'GC', 'Demand and messaging specialist', 'Proof either exists and is inspectable or it does not. NE does not apply to this element.',
   false, false, true, false, 9),
  ('0f6a0006-0000-4000-8000-000000000006', '2.4', 'element', '02', null, null, 'Consistency across every touchpoint, owned and unowned',
   'AI systems read every surface the company has published together and compress them into one answer. Two documents describing the ideal customer differently used to be untidy; now they are averaged.', 'Website, current deck, most recent outbound sequence, and at least two other owned surfaces. Unowned surfaces: directory listings, review sites, partner pages, job adverts. Answer-engine output for the prompts a buyer would use. Any audit record and its owner.', 'Owned and unowned surface audit; answer-engine spot-check; interview with marketing leadership',
   'GC', 'Demand and messaging specialist', 'Blend can always audit public surfaces without client input, so NE does not apply. Score what is publicly visible.',
   false, false, true, false, 10),
  ('0f6a0006-0000-4000-8000-000000000006', '2.5', 'element', '02', null, null, 'Sales and marketing message alignment in practice',
   'Alignment asserted in a process document is not alignment. What matters is what a rep says on a call and writes in an email.', 'Current shared sales assets and their version dates. Every rep-authored sales conversation available in the window: call transcripts where recording exists, otherwise written outreach and rep-authored decks. Marketing''s current narrative for comparison. Any defined update path from marketing to sales.', 'Asset comparison; sampled call or outreach review; interview with sales and marketing leadership',
   'GC', 'GA for call recording and sequence extracts', 'Work down the evidence ladder on the Sampling and Evidence Standard sheet and apply the cap it states for the tier reached.',
   true, true, false, false, 11),
  ('0f6a0006-0000-4000-8000-000000000006', 'H02', 'handoff', null, '02', '03', 'Message architecture into distribution',
   'What must travel: the message architecture and the proof library, every claim paired with the evidence that supports it and the persona it belongs to. The form: structured and machine-retrievable, so campaigns, sales tools and AI systems draw from one approved source. What breaks without it: every channel rewrites the story to fit its own format, and within two quarters the company is saying four different things in public.', 'The source channel owners actually work from. Retrievability test: ask whoever produced the most recent campaign asset and the most recent outbound sequence to show Blend what they drew from. Version count and last refresh date. Live channel content compared to the approved message.', 'Retrievability test with asset authors; live content comparison; interview with both sides of the join',
   'GC', 'Demand and messaging specialist', 'Both sides of a handoff are always available for interview, so NE does not apply.',
   false, false, true, true, 12),
  ('0f6a0006-0000-4000-8000-000000000006', '3.1', 'element', '03', null, null, 'Channel portfolio design and budget allocation logic',
   'Budget is allocated across channels that were inherited rather than chosen, and performance is judged campaign by campaign rather than as a portfolio.', '12 to 24 months of spend by channel and activity, budgeted and actual. Source and campaign attribution on opportunities. Any channel or GTM plan. Interview with marketing leadership and finance.', 'Document review; spend-to-opportunity reconciliation; CRM extract; interview',
   'GA', 'GC; finance interview led by GC', 'Where source or campaign attribution is absent on opportunities, cost per qualified opportunity cannot be computed. Cap at 2, confidence Low, and raise it as a Stage 1 data-quality flag.',
   true, false, false, false, 13),
  ('0f6a0006-0000-4000-8000-000000000006', '3.2', 'element', '03', null, null, 'Organic search foundation and content architecture',
   'Organic reach is the part of distribution the company still owns if paid spend stops. It compounds only where there is an architecture rather than a publishing habit.', 'Site crawl and technical health check. Content inventory with publication dates. Any keyword or topic mapping. Organic non-brand traffic and its contribution to pipeline. Interview with whoever owns content.', 'Technical audit; content inventory and coverage mapping against segment priority from 1.2; analytics and CRM review',
   'GA', 'Demand and messaging specialist', 'Blend can audit a public site without client input, so NE does not apply to the technical and architectural components.',
   true, false, true, false, 14),
  ('0f6a0006-0000-4000-8000-000000000006', '3.3', 'element', '03', null, null, 'Answer engine presence and citation share',
   'Buyers form shortlists inside AI systems the seller never sees. Presence there is a distribution question and for most companies it is currently unmanaged.', 'Blend''s own test across a prompt set representing the questions this segment''s buyers ask, run against the major assistants, capturing presence, accuracy and competitor citation. Any client monitoring record, prompt set and owner. Structured data and content adapted for citation.', 'Blend-run prompt testing; document review; interview with marketing leadership',
   'GC', 'Demand and messaging specialist', 'Blend runs this test independently, so NE does not apply. The prompt set used must be recorded in the report so the test is repeatable at re-score.',
   false, false, true, false, 15),
  ('0f6a0006-0000-4000-8000-000000000006', '3.4', 'element', '03', null, null, 'Paid media efficiency and payback discipline',
   'Paid spend is the easiest line to grow and the hardest to reduce once pipeline depends on it. Payback discipline is what keeps that dependence a choice.', 'Paid spend by channel and campaign, 12 to 24 months. Conversion tracking configuration. Opportunities attributed to paid, with value and close outcome. Brand and non-brand search spend separated. Any test record. Interview with whoever manages paid.', 'Platform and CRM reconciliation; cost per qualified opportunity and payback calculation; document review',
   'GA', 'GC', 'Where the client runs no paid media at all, mark NE and state the reason. This is one of the few legitimate NE cases in the instrument.',
   true, false, false, false, 16),
  ('0f6a0006-0000-4000-8000-000000000006', '3.5', 'element', '03', null, null, 'Partner, event, and community reach',
   'Events and partnerships are usually run as line items rather than as a reach strategy, so their contribution is never compared against the channels they compete with for budget.', 'Event and partner activity for 12 to 24 months with cost. Partner-sourced and partner-influenced pipeline as recorded in the CRM. Partner agreements and tiering. Any community or user group activity. Interview with whoever owns partnerships.', 'Document review; CRM extract of partner attribution; interview',
   'GC', 'GA for attribution extracts', 'Where the client has no partner or event activity, mark NE with the reason. Where activity exists but is untracked, that is a finding rather than NE.',
   true, false, true, false, 17),
  ('0f6a0006-0000-4000-8000-000000000006', 'H03', 'handoff', null, '03', '04', 'Reach into identified attention',
   'What must travel: reach converted into identified, contextualised attention. Who engaged, with what, from where, and what it implies about where they are in their thinking. The form: signals landing on a customer record, not figures landing in a channel report. What breaks without it: channel reporting stops at traffic and impressions and nobody can say who those people were.', 'Whether identified engagement, source and account context reach the record sales works from. Reconciliation between channel reporting and CRM records. Treatment of anonymous and account-level activity. Retrievability test on a recent opportunity.', 'System review across marketing platform and CRM; record-level sampling; interview with both sides',
   'GA', 'GC', 'Both sides of a handoff are always available for interview, so NE does not apply.',
   false, false, true, false, 18),
  ('0f6a0006-0000-4000-8000-000000000006', '4.1', 'element', '04', null, null, 'Website conversion architecture and next-step design',
   'A single book-a-demo call to action asks for commitment before most visitors are ready, which produces traffic and no conversation.', 'Full journey audit of the primary paths. All conversion points and what commitment each asks for. Conversion rates from visit to submission and submission to opportunity. Any test history. Interview with whoever owns the site.', 'Journey audit; analytics and CRM conversion analysis; document review; interview',
   'GA', 'GC; demand and messaging specialist', 'Where submission-to-opportunity cannot be traced because form submissions do not create CRM records, cap at 2 and raise the tracking gap as a finding.',
   true, false, true, false, 19),
  ('0f6a0006-0000-4000-8000-000000000006', '4.2', 'element', '04', null, null, 'Content-to-intent mapping across the research journey',
   'Content coverage clustered at one stage of the journey leaves buyers in active evaluation with nothing to read, which is the point at which they are choosing between vendors.', 'Content inventory with stage and persona tagging if it exists. Consumption paths for accounts that became opportunities, won and lost. Any content plan. Interview with content owner.', 'Content inventory; consumption path analysis from the marketing platform; document review',
   'GA', 'Demand and messaging specialist', 'Where consumption history is not retained beyond a short window, note the limitation, score on the inventory and mapping alone, and cap confidence at Medium.',
   true, false, true, false, 20),
  ('0f6a0006-0000-4000-8000-000000000006', '4.3', 'element', '04', null, null, 'Intent signal capture, scoring, and routing',
   'Optimising for contact capture produces volume sales learns to ignore. What matters is whether genuine intent is detected, weighted and acted on inside a defined time.', 'Scoring model configuration and its inputs. Routing rules and owners. Median and distribution of time from high-intent signal to first contact. Score against opportunity conversion. Any third-party or account-level intent source. Interview with marketing operations.', 'System configuration review; CRM and platform extract for response time and score-to-conversion analysis; interview',
   'GA', 'GC', 'Where timestamps do not support a response-time calculation, that absence is a finding. Cap at 2.',
   true, false, false, false, 21),
  ('0f6a0006-0000-4000-8000-000000000006', '4.4', 'element', '04', null, null, 'Always-on nurture and re-engagement programmes',
   'Contacts that are not ready today are the cheapest pipeline available later, and most companies mail them the same sequence regardless of behaviour or send them nothing at all.', 'All active nurture and re-engagement programmes with their entry criteria, branching logic and last content refresh date. Closed-lost and dormant account treatment. Contribution to qualified opportunity. Suppression and consent configuration.', 'System review of active programmes; performance extract; document review; interview with marketing operations',
   'GA', 'Demand and messaging specialist', 'Programmes either exist in the platform and are inspectable or they do not, so NE does not apply.',
   false, false, false, false, 22),
  ('0f6a0006-0000-4000-8000-000000000006', '4.5', 'element', '04', null, null, 'Qualification definition and the marketing-to-sales service level',
   'If sales ignores most of what marketing sends, the cause is a definition problem rather than an attitude problem, and it is visible in the acceptance data.', 'The written qualification definition, its author and date. Acceptance and rejection records. Response time against any stated service level. Conversion from handover to qualified opportunity. Separate interviews with marketing and sales leadership on how they each define a qualified lead.', 'Document review; CRM extract of acceptance, rejection and response time; paired interviews',
   'GC', 'GA for extracts', 'Interview both functions separately before comparing. A definition that exists on paper but produces different verbal answers from the two functions scores no higher than 2.',
   true, false, false, false, 23),
  ('0f6a0006-0000-4000-8000-000000000006', 'H04', 'handoff', null, '04', '05', 'Qualified opportunity into sales execution',
   'What must travel: the qualified opportunity together with its evidence. The research trail, the people involved, the likely trigger, and the reasoning behind the qualification. The form: a briefing the rep absorbs in sixty seconds, generated from the record rather than assembled by hand. What breaks without it: sales receives a name and a phone number, starts discovery from zero, and asks the buyer questions the company already knew the answers to.', 'Every handover in the window, examined for what was attached and what the rep then did. Time from signal to first contact. Whether reps read what travels, asked in interview. Any service level governing the handover.', 'Record-level sampling of recent handovers; response-time extract; interview with receiving reps as well as leadership',
   'GC', 'GA for the sampling extract', 'This is the join where the largest volume is lost, so read the records rather than rely on process description. Interview at least two receiving reps directly.',
   false, true, true, false, 24),
  ('0f6a0006-0000-4000-8000-000000000006', '5.1', 'element', '05', null, null, 'Pipeline stage definition and exit criteria discipline',
   'Stages that describe seller activity rather than buyer commitment cannot support a forecast, because nothing in them evidences that the buyer has moved.', 'Stage definitions and documented exit criteria. Stage history on won and lost opportunities for 24 months, examined for skipping and for time-in-stage distribution. Required fields or approvals enforcing criteria. Interview with sales leadership and two reps.', 'Document review; CRM stage-history analysis; configuration review; interview',
   'GA', 'GC', 'Where stage history is not retained, note it, score on definitions and current pipeline only, and cap at 3 with confidence Low.',
   true, false, false, false, 25),
  ('0f6a0006-0000-4000-8000-000000000006', '5.2', 'element', '05', null, null, 'Discovery and qualification consistency',
   'Performance variance between reps that nobody can explain is usually variance in discovery, and it is visible in what does and does not get recorded.', 'Discovery notes on every closed opportunity in the window, and call transcripts for all of them where recording exists, read for whether decision process, timeline and success criteria are recorded. Any discovery framework and training material. Evidence of a coaching loop.', 'Record and call sampling; document review; interview with sales leadership and two reps',
   'GC', 'GA for the sampling extract', 'Work down the evidence ladder on the Sampling and Evidence Standard sheet. Hand-score the validation set before trusting any classified rate.',
   true, true, false, false, 26),
  ('0f6a0006-0000-4000-8000-000000000006', '5.3', 'element', '05', null, null, 'Buyer enablement and mutual action planning',
   'Deals rarely die from a lost argument. They stall in an internal process the seller never saw, and mutual action planning is what makes that process visible.', 'Every closed opportunity in the window examined for recorded buying group, approval path, procurement and security requirements. Any mutual action plan template and evidence of use. Whether plans are shared with the buyer. Interview with sales leadership and two reps.', 'Record sampling; document review; interview',
   'GC', 'GA for extracts', 'Absence of a recorded buying group on the majority of sampled won deals caps this element at 2, regardless of any template in use.',
   true, false, false, false, 27),
  ('0f6a0006-0000-4000-8000-000000000006', '5.4', 'element', '05', null, null, 'Proposal, contracting, and procurement path design',
   'The gap between a buyer waiting ten days for a proposal and a buyer holding one in two hours is part of the product. Elapsed time here is measurable and almost never measured.', 'Proposal and contract templates. Standard commercial, legal and security positions. Approval path. Elapsed time from discovery call to proposal issued, and from proposal to signature, computed from the client''s own records. Interview with sales leadership, legal or finance.', 'Document review; elapsed-time calculation from CRM and document timestamps; interview',
   'GA', 'GC', 'Where proposal issue dates are not recorded, reconstruct from document or email timestamps across the window, state the method, and cap confidence at Medium.',
   true, false, false, false, 28),
  ('0f6a0006-0000-4000-8000-000000000006', '5.5', 'element', '05', null, null, 'Forecast accuracy and pipeline hygiene',
   'Forecast accuracy is a proxy for management quality. A team that can call the quarter inside a narrow band is telling you their system works.', 'Forecast submissions for the last four quarters and the actual outcome of each. Current open pipeline examined for past close dates, stale activity and missing required fields. Coverage ratio and how it was set. Interview with sales leadership and finance.', 'Forecast-to-actual analysis; pipeline hygiene extract; document review; interview',
   'GA', 'GC; finance interview led by GC', 'Where no forecast history is retained, accuracy cannot be computed. Score no higher than 1 and state that the absence of retained forecast history is itself the finding.',
   true, false, false, false, 29),
  ('0f6a0006-0000-4000-8000-000000000006', 'H05', 'handoff', null, '05', '06', 'What was sold into what gets delivered',
   'What must travel: what was actually sold. Scope, commitments, success criteria, the people involved, and every promise made in the room that is not in the contract. The form: a structured deal record that becomes the onboarding plan directly. What breaks without it: delivery discovers what sales promised after the customer has already been told when it will be ready.', 'The handover record for every closed-won deal in the window, examined for scope, commitments, success criteria and named stakeholders. Evidence of commitments surfacing after work began. Whether delivery re-keys the record into a separate plan. Interview with both sides of the join.', 'Record-level census of closed-won handovers; onboarding artefact comparison; interview',
   'GC', 'GA for the census extract', 'Both sides of a handoff are always available for interview, so NE does not apply. Where no handover artefact exists at all, that is a level 0 finding rather than NE.',
   false, true, true, false, 30),
  ('0f6a0006-0000-4000-8000-000000000006', '6.1', 'element', '06', null, null, 'Sales-to-delivery handoff integrity',
   'This element assesses what delivery does with what arrives: whether intake is structured, whether gaps are caught, and whether acceptance is conditional. H05 assesses the contract itself. Score them separately and do not let one justify the other.', 'Delivery intake process and checklist. Records of gaps found at intake and what happened to them. Onboarding artefacts for recent implementations compared against the deal record. Interview with delivery or customer success leadership and one implementation lead.', 'Document review; artefact comparison across recent onboardings; interview',
   'GC', 'Revenue operations specialist', 'Where no intake artefact exists, score on the onboarding record and interview and cap confidence at Medium.',
   true, true, false, false, 31),
  ('0f6a0006-0000-4000-8000-000000000006', '6.2', 'element', '06', null, null, 'Onboarding design and time-to-first-value',
   'Time-to-first-value is the most reliable early predictor of retention available, and it is decided almost entirely by operational decisions in the first 60 days.', 'The definition of first value, if one exists, and how it is measured. Onboarding process documentation. Start and first-value dates for every customer onboarded in the window. Retention outcome by onboarding cohort. Interview with delivery leadership.', 'Document review; census of onboarding durations; cohort retention analysis; interview',
   'GA', 'GC', 'Where first value is undefined, duration cannot be computed against it. Score no higher than 1 and report the absence of a definition as the finding.',
   true, false, false, false, 32),
  ('0f6a0006-0000-4000-8000-000000000006', '6.3', 'element', '06', null, null, 'Adoption and usage tracking',
   'Adoption data that never reaches the customer-facing team leaves account reviews running on what the customer chooses to say.', 'Available usage or delivery telemetry and whether it reaches the customer-facing team. The behaviours tracked and how they were chosen. Adoption against renewal and expansion outcomes. Interview with customer success leadership and product or delivery operations.', 'System review; adoption-to-outcome analysis across the base; interview',
   'GA', 'Revenue operations specialist', 'For a tech-enabled services business with no product telemetry, substitute delivery milestone and engagement data and state the substitution. NE does not apply.',
   true, false, false, false, 33),
  ('0f6a0006-0000-4000-8000-000000000006', '6.4', 'element', '06', null, null, 'Health scoring and early-warning signals',
   'A health score that did not flag the accounts that churned is a dashboard rather than a warning system, and that is testable against the client''s own churn history.', 'Health score definition and inputs. Historic health status for every account that churned in the window, read back to establish whether and when it flagged. Thresholds and the actions they trigger. Interview with customer success leadership.', 'System review; retrospective test of the score against all churned accounts; interview',
   'GA', 'GC', 'Where historic health status is not retained, the score cannot be tested. Cap at 2, confidence Low, and record the retention gap as a finding.',
   true, false, false, false, 34),
  ('0f6a0006-0000-4000-8000-000000000006', '6.5', 'element', '06', null, null, 'Escalation, recovery, and save motion',
   'Save motions run case by case teach the business nothing. Recorded outcomes and root causes send the cause back to the function that owns it.', 'Escalation path and severity definitions. All escalations and attempted saves in the window with outcome and recorded cause. Save rate. Interview with customer success leadership and support.', 'Document review; census of escalation and save records; interview',
   'GC', 'Revenue operations specialist', 'Where escalations are not recorded as a distinct object, reconstruct from support tickets and account notes, state the method, and cap confidence at Medium.',
   true, false, false, false, 35),
  ('0f6a0006-0000-4000-8000-000000000006', 'H06', 'handoff', null, '06', '07', 'Delivered value into captured proof',
   'What must travel: evidence that value was actually delivered. The measurable outcome, who inside the account saw it, and when it happened. The form: a captured success signal with a timestamp. What breaks without it: marketing reconstructs a case study fourteen months later from a happy email, and the customer no longer remembers the numbers.', 'Whether delivered outcomes are recorded with a measure, a named witness and a date, and whether the team that produces proof can retrieve them without asking. Retrievability test: ask whoever produced the most recent case study to show Blend where the numbers came from.', 'Retrievability test; census of accounts in the window for recorded outcomes; interview with both sides',
   'GC', 'GA for the census extract', 'Both sides of a handoff are always available for interview, so NE does not apply.',
   false, false, true, true, 36),
  ('0f6a0006-0000-4000-8000-000000000006', '7.1', 'element', '07', null, null, 'Voice-of-customer capture and success signal instrumentation',
   'Nearly every B2B business has more satisfied customers than usable proof, because satisfaction sits in people''s heads rather than on a record.', 'All voice-of-customer mechanisms and their cadence. Retrievable list of quantified customer outcomes from the window, with coverage across the base. How and when success moments get recorded. Interview with customer success and marketing leadership.', 'System and document review; census of accounts for recorded outcomes; interview',
   'GC', 'Revenue operations specialist', 'Coverage is measured against the whole customer base, not against the accounts that happen to have a record. Report the proportion.',
   true, false, false, false, 37),
  ('0f6a0006-0000-4000-8000-000000000006', '7.2', 'element', '07', null, null, 'Reference and case study engine',
   'Reference hunting the week a reference is needed is the symptom. The engine is whether production runs on a cadence against a coverage map.', 'All case studies with date, segment and whether outcomes are quantified. Reference list with permission status and usage history. Production cadence and owner. Coverage mapped against the segment priority from 1.2. Interview with marketing leadership.', 'Full inventory and coverage mapping; document review; interview',
   'GC', 'Demand and messaging specialist', 'Proof either exists and is inspectable or it does not, so NE does not apply.',
   true, false, true, false, 38),
  ('0f6a0006-0000-4000-8000-000000000006', '7.3', 'element', '07', null, null, 'Referral mechanics and incentives',
   'Referral-sourced pipeline is the highest-quality revenue in most businesses and the most underbuilt, and it is usually invisible because no source value distinguishes it.', 'Whether referral is a distinguishable source on opportunities. All referred pipeline in the window with conversion and value against other sources. Any defined ask, mechanic or incentive. Interview with sales and customer success leadership.', 'CRM census of referred pipeline; document review; interview',
   'GA', 'GC', 'Where referral is not a recorded source, its contribution cannot be measured. Cap at 1 and report the tracking gap as the finding.',
   true, false, false, false, 39),
  ('0f6a0006-0000-4000-8000-000000000006', '7.4', 'element', '07', null, null, 'Advocacy, community, and customer-led content',
   'Advocacy resting on individual relationships leaves with the individual. A programme survives the account manager changing.', 'Any advocacy programme, advocate list and tiering. Customer-led content produced in the window. Community or user group activity and its management. Contribution to pipeline where tracked. Interview with marketing and customer success leadership.', 'Document review; content inventory; interview',
   'GC', 'Demand and messaging specialist', 'Where no advocacy activity exists at all, that is a level 0 finding rather than NE.',
   false, false, true, false, 40),
  ('0f6a0006-0000-4000-8000-000000000006', '7.5', 'element', '07', null, null, 'Satisfaction measurement tied to a defined action',
   'Satisfaction collected, reported and then connected to nothing is a cost with no return. What matters is whether a response changes anyone''s day.', 'Survey instrument, cadence and response rate. Defined follow-up per response type and evidence of closure. Satisfaction analysed against renewal and expansion outcomes. Interview with customer success leadership.', 'System and document review; census of responses against recorded follow-up; interview',
   'GC', 'Revenue operations specialist', 'Where no satisfaction measurement runs at all, mark level 0 rather than NE.',
   false, false, false, false, 41),
  ('0f6a0006-0000-4000-8000-000000000006', 'H07', 'handoff', null, '07', '08', 'Advocacy into a commercial opening',
   'What must travel: advocacy converted into a specific opening. Which customers are delighted, about what, and which account team should act on it this week. The form: a triggered task carrying its own context. What breaks without it: a glowing survey response and an expansion conversation never meet, and the goodwill expires unused.', 'All strong satisfaction or advocacy signals in the window, traced forward to whether any commercial conversation followed and how quickly. What context travels with a flag. Interview with both sides of the join.', 'Signal-to-action traceability census; system review; interview',
   'GC', 'GA for the traceability extract', 'Both sides of a handoff are always available for interview, so NE does not apply.',
   false, false, true, false, 42),
  ('0f6a0006-0000-4000-8000-000000000006', '8.1', 'element', '08', null, null, 'White space and wallet share mapping',
   'Expansion cannot be prioritised until white space is both known and valued, and in most companies it is neither.', 'Product or service ownership per account from the system of record. Any white space mapping, how it is maintained and where it is visible. Whether opportunity is valued. Interview with sales and customer success leadership.', 'CRM census of ownership; document review; interview',
   'GA', 'Revenue operations specialist', 'Ownership data is always retrievable in some form, so NE does not apply. Where it sits outside the CRM, note where it sits as a finding.',
   false, false, false, false, 43),
  ('0f6a0006-0000-4000-8000-000000000006', '8.2', 'element', '08', null, null, 'Expansion trigger design and signal routing',
   'The share of expansion revenue that was triggered by a signal rather than requested by the customer is the number that shows whether a system exists.', 'Any defined triggers, whether they are instrumented, and where they route. All expansion events in the window classified as customer-initiated or company-initiated. What preceded past expansions, analysed by Blend. Interview with sales and customer success leadership.', 'Census of expansion events and their origin; antecedent analysis; system review; interview',
   'GA', 'GC', 'Where expansion events cannot be distinguished from new business in the record, reconstruct from contract or invoice data, state the method, and cap confidence at Medium.',
   true, false, false, false, 44),
  ('0f6a0006-0000-4000-8000-000000000006', '8.3', 'element', '08', null, null, 'Cross-sell and upsell plays by segment',
   'Generic expansion material asks the account team to invent the argument each time, which is why expansion conversations tend to be improvised.', 'All expansion-specific material and how it is differentiated by segment and current ownership. Conversion and value by expansion path across the window. Interview with sales leadership.', 'Document review; census of expansion opportunities by path; interview',
   'GC', 'GA for path analysis', 'Where expansion path is not recorded, derive it from product ownership before and after, state the method, and cap confidence at Medium.',
   true, false, false, false, 45),
  ('0f6a0006-0000-4000-8000-000000000006', '8.4', 'element', '08', null, null, 'Renewal management and gross retention discipline',
   'Gross retention is the cleanest read on product and delivery quality, and cross-sell attempted at renewal is the worst possible timing.', 'Renewal process documentation and its defined start point. All renewals in the window with outcome, timing of first contact, and recorded non-renewal reason. Gross and net retention reported separately and cohorted. Interview with customer success and finance.', 'Document review; census of renewals and their timing; retention cohort analysis; interview',
   'GA', 'GC; finance interview led by GC', 'Where gross and net retention are conflated in reporting, compute both from the raw records and report the conflation as a finding.',
   true, false, false, false, 46),
  ('0f6a0006-0000-4000-8000-000000000006', '8.5', 'element', '08', null, null, 'Account planning and executive review cadence',
   'Account plans that exist as documents and get reviewed annually are a record of intent rather than an operating rhythm.', 'Account plans for the priority accounts with authorship and revision dates. Executive review cadence and recorded decisions with owners. Whether plans draw on white space, health and trigger data. Interview with sales and customer success leadership.', 'Document review; revision history check; interview',
   'GC', 'Revenue operations specialist', 'Where no account plans exist, mark level 0 rather than NE.',
   true, false, false, false, 47),
  ('0f6a0006-0000-4000-8000-000000000006', 'H08', 'handoff', null, '08', '01', 'Renewal evidence into who you are for',
   'What must travel: renewal and expansion evidence. Who expanded, who churned, and what predicted each of them well before it happened. The form: a scheduled input into ICP and segment review. What breaks without it: the company keeps selling to a stated ICP that its own renewal data has been quietly contradicting for two years. This is the join that decides whether the company gets sharper or drifts.', 'Whether renewal, churn and expansion outcomes reach ICP and segment review, on what schedule, and whether predictors are identified rather than outcomes alone. Any recorded change to targeting or qualification traceable to that evidence. Interview with both sides of the join.', 'Document review; traceability check from retention evidence to a targeting change; interview',
   'GC', 'GA', 'Read this handoff alongside the ICP Reconciliation result. A high variance rate with a level 4 or 5 score here is a contradiction: re-check both before publishing.',
   false, false, true, false, 48);

insert into anchor (element_id, level, descriptor)
select e.id, v.level, v.descriptor from (values
  ('1.1', 0, 'No ICP document is produced on request. Interviews return three or more materially different descriptions of the target customer, with no source anyone can point to as authoritative.'),
  ('1.1', 1, 'An ICP description exists in a deck or wiki page. It has no named author, no review date inside 24 months, and no reference to customer data. Criteria are firmographic only: size, industry, geography.'),
  ('1.1', 2, 'A written ICP exists, is dated inside 24 months, and adds behavioural or situational criteria beyond firmographics. No reconciliation against closed-won or renewal data has ever been performed by the client, and the ICP Reconciliation sheet returns variance the client cannot account for.'),
  ('1.1', 3, 'Written ICP with exclusion criteria stated as well as inclusion criteria. Blend''s reconciliation shows the stated ICP and the closed-won population agree on the majority of criteria tested. The client had not run that reconciliation themselves.'),
  ('1.1', 4, 'The client evidences its own reconciliation against closed-won and renewal data inside the last 12 months, and can show at least one criterion that changed as a result. Exclusions are as specific as inclusions.'),
  ('1.1', 5, 'As level 4, and the ICP is held in one governed, machine-retrievable record that marketing, sales and customer success demonstrably read from — evidenced by direct reference in live campaign briefs, qualification criteria and onboarding documentation. Reconciliation runs on a defined cadence with a named owner.'),
  ('1.2', 0, 'No segmentation beyond a target account list. No stated priority order, and interviews produce different answers on which segment matters most.'),
  ('1.2', 1, 'Segments are named in a plan but the priority order cannot be traced to any input. Sizing, where present, is a top-down analyst market figure with no bottom-up derivation.'),
  ('1.2', 2, 'Segments named with a stated priority and some sizing. Sizing rests on third-party market figures only; no bottom-up count of qualifying accounts exists. Priority order does not correspond to observed win rate or retention by segment.'),
  ('1.2', 3, 'A bottom-up qualifying account count exists for at least the top two segments. Blend''s analysis finds the stated priority order broadly consistent with win rate by segment, though the client had not tested this themselves.'),
  ('1.2', 4, 'The client evidences its own segment-level economics — win rate, ACV, and gross retention, with CAC where available — and the priority order follows them. Deprioritised segments are explicitly named.'),
  ('1.2', 5, 'As level 4, and segment priority is reviewed on a defined cadence against actual cohort performance, coverage is planned against the bottom-up qualifying account count, and at least one reprioritisation decision inside 12 months traces directly to that review.'),
  ('1.3', 0, 'No win/loss or churn records available in structured form. Loss reason is absent from the majority of closed-lost records, or churn is tracked only as a revenue number with no attribution.'),
  ('1.3', 1, 'Closed-lost reasons are captured but a catch-all value — no decision, other, price — accounts for more than half of records. Churn reasons sit in narrative fields or nowhere. No analysis is performed on either.'),
  ('1.3', 2, 'Two years of closed-won, closed-lost and churn records are retrievable and reasonably complete. Analysis is anecdotal: recent deals discussed in a pipeline review rather than pattern cut by segment, product, deal size or partner involvement.'),
  ('1.3', 3, 'Blend can cut the data and find stable patterns. The client conducts periodic win/loss review but without structured buyer-side interviews. Churn is reviewed by customer success separately from win/loss review by sales, with no shared conclusion.'),
  ('1.3', 4, 'The client runs structured win/loss review including at least some buyer-side interviews, cuts churn by cohort, and can name a specific decision that changed as a result.'),
  ('1.3', 5, 'As level 4, and win/loss and churn findings are a scheduled input into ICP and messaging review with a named owner. The loop is evidenced by a dated change to targeting or qualification criteria traceable to a specific finding.'),
  ('1.4', 0, 'No differentiation statement exists. Interviews produce different competitor sets and no consistent answer to why the company wins.'),
  ('1.4', 1, 'Differentiation exists as adjectives: flexible, easy to use, partner rather than vendor. Blend''s substitution test — inserting a named competitor into each claim — leaves every claim true.'),
  ('1.4', 2, 'Differentiation is specific in one or two places, such as a capability, an integration or a compliance position. No claim is paired with retrievable evidence, and competitor claims have not been reviewed inside 12 months.'),
  ('1.4', 3, 'At least two differentiators survive the substitution test and are supported by evidence Blend can retrieve. Competitive review is ad hoc, and win/loss data has not been used to test whether the stated differentiators are the ones buyers actually cite.'),
  ('1.4', 4, 'Stated differentiators reconcile against the reasons cited in closed-won records or buyer interviews. The client maintains a current competitive picture with a dated review, and can name the situations in which it does not win.'),
  ('1.4', 5, 'As level 4, and differentiation claims are held once in a governed record with evidence attached, referenced by both marketing assets and sales qualification, and tested against win/loss evidence on a defined cadence.'),
  ('1.5', 0, 'No consistent price book. Pricing is set deal by deal and no two closed-won records of comparable scope agree.'),
  ('1.5', 1, 'A price book exists but discounting shows no pattern explicable by segment, volume or term. The last structural review of packaging is more than three years ago or cannot be dated.'),
  ('1.5', 2, 'Price book current and discount governance exists on paper. Blend''s analysis of realised pricing shows dispersion the client cannot account for, and packaging boundaries do not correspond to how the prioritised segments buy.'),
  ('1.5', 3, 'Realised pricing is explicable by segment and term, and packaging maps to segments reasonably well. No margin or win-rate analysis by package exists, and willingness-to-pay input goes no further than sales anecdote.'),
  ('1.5', 4, 'The client evidences package-level margin and win-rate analysis, and at least one packaging or pricing change inside 24 months traces to it. Discount authority is defined and adhered to in the data.'),
  ('1.5', 5, 'As level 4, and pricing and packaging are reviewed against cohort expansion and retention outcomes rather than new-sale win rate alone, with a named owner and a defined cadence.'),
  ('H01', 0, 'Nothing travels. The people who write messaging cannot name a document or data source that defined the target customer. The two stages have no connection.'),
  ('H01', 1, 'Transfer happens verbally, or through a single offsite deck. No stage 01 output is retrievable by the people doing stage 02 work when Blend asks them to produce it.'),
  ('H01', 2, 'An ICP document is handed over but carries firmographics only. The reasons best-fit customers chose the company do not travel at all: win/loss evidence stays inside sales.'),
  ('H01', 3, 'ICP, segment priority and some win reasons travel in retrievable documents. Multiple copies exist in different places, and Blend finds at least two versions in current use.'),
  ('H01', 4, 'One authoritative record carries the evidenced ICP, the segment priority and cited win reasons, and the people producing messaging can show Blend they worked from it.'),
  ('H01', 5, 'As level 4, in a governed machine-retrievable form with a named owner, refreshed on a defined cadence whenever stage 01 evidence changes, and consumed by both people and tooling.'),
  ('2.1', 0, 'No written narrative. Leadership interviews produce materially different accounts of what the company does and who it is for.'),
  ('2.1', 1, 'A positioning statement exists in a deck. It describes the company''s own activities rather than the buyer''s situation, and has no named owner or review date.'),
  ('2.1', 2, 'A written narrative is current and owned. It states a problem, but in category-generic terms, and Blend''s substitution test leaves it true for named competitors. No proof is attached to any claim.'),
  ('2.1', 3, 'The narrative names a specific buyer situation and survives the substitution test. It exists in one authoritative place, but interviews show senior stakeholders paraphrasing it differently in practice.'),
  ('2.1', 4, 'The narrative is specific, evidenced, and reproduced consistently by the people Blend interviews across at least marketing and sales. It carries a dated review and a named owner.'),
  ('2.1', 5, 'As level 4, and the narrative is held in a governed, machine-retrievable record that downstream assets and AI tooling demonstrably draw from. It has been revised on stage 01 evidence inside the last 12 months.'),
  ('2.2', 0, 'No persona definitions exist. One message is used for all audiences.'),
  ('2.2', 1, 'Personas exist as job titles with demographic detail. No message differentiation traceable to them appears in live assets.'),
  ('2.2', 2, 'Personas are defined with stated pains and goals, and persona messaging exists in a document. Blend cannot find it expressed in live assets: the website and outbound speak to a single generic buyer.'),
  ('2.2', 3, 'Persona-level messaging is visible in live assets for the primary persona. Secondary and blocking personas — finance, IT, procurement, security — are not addressed. Persona definitions have not been reconciled against the buying groups visible in closed-won records.'),
  ('2.2', 4, 'Messaging is differentiated across the personas that actually appear in the client''s own closed-won buying groups, evidenced in live assets, with buying-group composition derived from CRM contact roles rather than assumption.'),
  ('2.2', 5, 'As level 4, and the persona architecture is governed centrally. Conversion from first meaningful engagement to qualified opportunity is measured by persona and used to revise the architecture on a cadence.'),
  ('2.3', 0, 'No case studies, quantified outcomes or reference list. Proof consists of a logo wall.'),
  ('2.3', 1, 'Case studies exist but carry no client-verified numbers, or the newest is more than 24 months old. References are located by asking around when one is needed.'),
  ('2.3', 2, 'Quantified case studies exist. Coverage is uneven and does not match current segment priority: Blend''s mapping shows the majority of proof sitting in segments the client no longer prioritises. No reference inventory exists.'),
  ('2.3', 3, 'Proof coverage matches the top segments and claims are traceable to a source. Production is project-based rather than continuous, and a named reference is available for some segments but not on demand.'),
  ('2.3', 4, 'A maintained proof library pairs each claim with its evidence and the persona it belongs to, covers every priority segment, and has a defined production cadence and a current reference inventory by segment.'),
  ('2.3', 5, 'As level 4, and the proof library is governed and machine-retrievable, so campaigns, sales assets and AI tooling draw from the same approved set. Success signals from delivery and advocacy feed it on a schedule.'),
  ('2.4', 0, 'Blend''s audit finds materially different descriptions of what the company does across the website, the current pitch deck and the most recent outbound sequence.'),
  ('2.4', 1, 'Owned surfaces are broadly consistent in tone and inconsistent in substance: different value claims, different target buyer, different product boundaries. Unowned surfaces have never been reviewed.'),
  ('2.4', 2, 'Owned surfaces are consistent. Unowned surfaces — directory listings, review sites, partner pages, job adverts, answer-engine output — have not been audited, and Blend''s spot-check finds at least one materially outdated or contradictory public description.'),
  ('2.4', 3, 'Owned surfaces are consistent and reviewed. The client has looked at what answer engines say about it at least once, informally. There is no correction process and no owner for unowned surfaces.'),
  ('2.4', 4, 'Owned and unowned surfaces have been audited inside 12 months with a named owner, corrections have been actioned, and answer-engine output has been checked against the approved positioning.'),
  ('2.4', 5, 'As level 4, and a governed source feeds owned surfaces while unowned surfaces are monitored on a cadence. Drift is detected and corrected through a defined process rather than on accidental discovery.'),
  ('2.5', 0, 'Every rep uses their own deck. Blend can find no shared current sales asset.'),
  ('2.5', 1, 'A shared deck exists and is out of date relative to marketing''s current positioning; reps say so in interview. Blend''s comparison of the two finds different core claims.'),
  ('2.5', 2, 'Shared, current assets exist. Blend''s review of live collateral, call recordings or outbound copy shows reps substituting their own framing on the core claim in the majority of cases sampled.'),
  ('2.5', 3, 'Sampled sales conversations and assets align with the marketing narrative on the core claim, diverging on proof points and objection handling. There is no shared source: both functions maintain their own copies.'),
  ('2.5', 4, 'Sales and marketing demonstrably draw from one source for narrative, proof and objection handling. Alignment is evidenced in sampled calls or assets rather than asserted as process.'),
  ('2.5', 5, 'As level 4, and alignment is maintained by a defined update path with a named owner. Message changes reach live sales conversations inside a stated period, and the sampling that verifies this happens on a cadence.'),
  ('H02', 0, 'Nothing travels. The people producing channel content cannot name an approved message source, and Blend finds materially different core claims between channels.'),
  ('H02', 1, 'Messaging reaches channels through a deck or a briefing conversation. No proof library exists, so each channel sources its own evidence.'),
  ('H02', 2, 'An approved message document exists and reaches channel owners. Proof does not travel with it: claims appear in channel content without supporting evidence attached, and Blend finds at least one unsupported claim in live material.'),
  ('H02', 3, 'Message architecture and a proof set both travel in retrievable documents. Persona pairing is partial, copies are duplicated across teams, and Blend finds more than one version in current use.'),
  ('H02', 4, 'One authoritative source carries the message architecture with each claim paired to its evidence and the persona it belongs to, and channel owners can show Blend they worked from it.'),
  ('H02', 5, 'As level 4, in governed machine-retrievable form with a named owner, consumed by campaigns, sales tooling and AI systems alike, and refreshed on a defined cadence whenever stage 02 changes.'),
  ('3.1', 0, 'No channel plan. Spend allocation cannot be reconstructed from any document, and interviews produce different accounts of why money sits where it does.'),
  ('3.1', 1, 'Spend is recorded by channel but no channel has a stated job. Allocation traces to last year''s allocation and nothing else.'),
  ('3.1', 2, 'Channels have stated roles in a plan and allocation is argued from channel-level cost per lead. Blend''s analysis finds spend concentrated in channels whose contribution to qualified pipeline the client cannot evidence.'),
  ('3.1', 3, 'Each channel has a stated job and allocation is argued from cost per qualified opportunity rather than cost per lead. The portfolio is reviewed periodically. No payback period is calculated and channel concentration risk has not been quantified.'),
  ('3.1', 4, 'Allocation is set against cost per qualified opportunity and payback by channel, computed from the client''s own data. Channel concentration is quantified and stated. At least one reallocation decision inside 12 months traces to the analysis.'),
  ('3.1', 5, 'As level 4, and the portfolio is reviewed on a defined cadence against a single source of channel contribution with a named owner. Owned and paid reach are planned as a deliberate mix, and the company holds a documented position on what reach it would still own if paid spend stopped.'),
  ('3.2', 0, 'No organic strategy. Blend''s crawl finds no topical structure, and organic non-brand traffic is negligible or unmeasurable.'),
  ('3.2', 1, 'Content is published without an architecture. No keyword or topic mapping exists, and technical foundations show unresolved issues Blend can name: indexation, speed, or thin and duplicated templates.'),
  ('3.2', 2, 'Keyword targeting exists at page level. There is no topic cluster or internal linking architecture, production is driven by campaign need rather than a coverage map, and non-brand organic contribution to pipeline is not measured.'),
  ('3.2', 3, 'A topic architecture exists and technical foundations are sound. Coverage maps loosely to the priority segments from 1.2. Organic contribution is measured to traffic but not through to qualified opportunity.'),
  ('3.2', 4, 'Content architecture is mapped to the priority segments and personas, technical health is monitored, and organic non-brand contribution is measured through to qualified opportunity.'),
  ('3.2', 5, 'As level 4, and the architecture is maintained against a coverage map with a named owner and cadence, drawing on the same governed messaging and proof source as every other channel, and refreshed on performance evidence rather than volume targets.'),
  ('3.3', 0, 'No awareness of how the company appears in AI-generated answers. Nobody has looked, and Blend''s prompt test finds the company absent or materially misdescribed across the majority of the set.'),
  ('3.3', 1, 'Someone has typed the company name into an assistant informally. There is no record, no prompt set, no view of which competitors are cited instead, and no action has followed.'),
  ('3.3', 2, 'A one-off check has been documented. Blend''s own test across the prompts a buyer would actually use finds the company absent from the majority, or described inaccurately, with no remediation underway.'),
  ('3.3', 3, 'The client tracks presence against a defined prompt set at least occasionally and has identified accuracy issues. There is no owner, no cadence, and content and structured data have not been adapted for citation.'),
  ('3.3', 4, 'A defined prompt set is monitored on a cadence with citation share tracked against named competitors. Content and structured data have been adapted for citation, and at least one accuracy correction is evidenced.'),
  ('3.3', 5, 'As level 4, and the prompt set is derived from actual buyer language rather than assumption, monitored with a named owner, and the answers draw on a governed source that keeps the company''s description accurate wherever it is read.'),
  ('3.4', 0, 'Paid spend is running with no conversion tracking Blend can verify. Performance is reported on platform metrics alone.'),
  ('3.4', 1, 'Conversion tracking reaches form submission only. There is no connection between spend and opportunities in the CRM, and reporting stops at cost per lead.'),
  ('3.4', 2, 'Spend connects to CRM records for some channels. Blend can part-compute cost per qualified opportunity but the client cannot. No payback period is calculated, and brand and non-brand search spend are not separated.'),
  ('3.4', 3, 'Cost per qualified opportunity is computed by the client for the main paid channels and payback is estimated. Test discipline is absent: creative and audience changes are not held long enough or measured cleanly enough to attribute a result.'),
  ('3.4', 4, 'Cost per qualified opportunity and payback period are computed per paid channel from CRM data with brand and non-brand separated, and a documented test cadence shows decisions traceable to test outcomes.'),
  ('3.4', 5, 'As level 4, and paid is managed against a payback threshold agreed with finance, reviewed on a cadence with a named owner, with its role in the portfolio stated relative to what owned channels are expected to carry over time.'),
  ('3.5', 0, 'Partner, event and community activity either does not happen or happens with no record and no owner.'),
  ('3.5', 1, 'Events and partner activity run as line items. Cost is known, contribution is not tracked, and the same activity recurs annually without review.'),
  ('3.5', 2, 'Some contribution tracking exists for events. Partner-sourced and partner-influenced pipeline are not distinguished, or partner activity is not recorded in the CRM at all, and no activity has a stated reach objective.'),
  ('3.5', 3, 'Partner and event contribution is tracked to pipeline and each activity has a stated objective. Tiering or joint plans exist for the largest relationships only, and community is unmanaged.'),
  ('3.5', 4, 'Partner-sourced and partner-influenced pipeline are tracked separately, event contribution is measured through to qualified opportunity, and activity selection is argued from prior performance rather than habit.'),
  ('3.5', 5, 'As level 4, and reach through partners, events and community is planned as a portfolio with a named owner and cadence, with partner-facing messaging drawn from the same governed source as owned channels.'),
  ('H03', 0, 'Nothing travels beyond aggregate channel metrics. No engagement is attached to an identifiable account or contact record.'),
  ('H03', 1, 'Form submissions reach the CRM with a source value. Pre-conversion behaviour is not attached to the record, and channel reporting and CRM records cannot be reconciled to each other.'),
  ('H03', 2, 'Source and campaign attach to contacts. Engagement history sits in the marketing platform and does not reach the record sales works from, and anonymous or account-level activity is discarded.'),
  ('H03', 3, 'Engagement history and source attach to the contact and account record. Attribution is single-touch, and the implication of the behaviour is left for a human to interpret with no summary present on the record.'),
  ('H03', 4, 'Identified engagement, source and account-level context all land on one record with a usable summary of what was consumed and when, reconcilable to channel reporting.'),
  ('H03', 5, 'As level 4, and the record carries a contextual interpretation generated automatically and refreshed continuously, with a named owner for the signal definitions and a cadence for reviewing them.'),
  ('4.1', 0, 'The site offers no path to a conversation beyond a contact page, or Blend''s audit finds primary journeys broken.'),
  ('4.1', 1, 'A single next step across the whole site, typically book a demo or contact us. Conversion is not measured beyond form submissions, and submissions cannot be distinguished by intent.'),
  ('4.1', 2, 'Multiple forms exist but all ask for the same level of commitment. Nothing is offered to a visitor in early research. Conversion is measured to submission, and submission-to-opportunity rate is either unmeasured or at a level the client cannot explain.'),
  ('4.1', 3, 'Next steps are differentiated by research stage on the main journeys, and conversion is measured through to opportunity for the primary path. Secondary journeys and high-intent pages are not instrumented, and there is no test record.'),
  ('4.1', 4, 'Next steps are matched to research stage across the priority journeys, conversion is measured through to qualified opportunity by path, and a documented test history shows changes made on evidence.'),
  ('4.1', 5, 'As level 4, and the conversion architecture is reviewed on a cadence against measured path performance with a named owner, with page content drawing on the governed messaging and proof source rather than being separately authored.'),
  ('4.2', 0, 'No mapping of content to buying stage, and a content inventory cannot be produced.'),
  ('4.2', 1, 'Content exists in volume with no stage mapping. Blend''s inventory finds coverage clustered at one stage, usually early research, with little available to a buyer in active evaluation.'),
  ('4.2', 2, 'Content is loosely tagged by stage. The mapping is asserted rather than derived: no analysis has tested what the accounts that became opportunities actually consumed.'),
  ('4.2', 3, 'Content is mapped to stage and persona and gaps are known. The client has not tested the map against actual consumption paths in their own data, which Blend does as part of this element.'),
  ('4.2', 4, 'The mapping is validated against consumption evidence from won and lost opportunities, gaps are prioritised, and production is planned against the map rather than against a calendar.'),
  ('4.2', 5, 'As level 4, and the map is maintained on a cadence with a named owner, refreshed from consumption and conversion evidence, with every asset traceable to the governed proof and messaging source.'),
  ('4.3', 0, 'No signal capture beyond form submissions. No scoring and no routing rules: enquiries reach sales by whoever notices first.'),
  ('4.3', 1, 'Form submissions route by round robin or territory with no signal weighting. Behavioural data is collected by the platform and unused. Response time is not measured.'),
  ('4.3', 2, 'A lead score exists. Blend''s review finds it weighted on demographic fit or raw activity volume rather than evidenced buying behaviour, no analysis has tested score against conversion, and response time is not measured.'),
  ('4.3', 3, 'Scoring includes behavioural signals and routing is automated with a defined owner per route. Median response time to a high-intent signal is measurable and known. The score has not been validated against conversion outcomes, and account-level or third-party intent is not used.'),
  ('4.3', 4, 'Scoring is validated against opportunity conversion and revised on that evidence. High-intent routing is automated with response time measured against a stated target. First-party signals are combined with account-level intent where available.'),
  ('4.3', 5, 'As level 4, and the signal model is reviewed on a cadence with a named owner, routing carries context to the receiving rep automatically, and the definition of intent is held once and consumed by every system that acts on it.'),
  ('4.4', 0, 'No nurture. Contacts that do not convert receive nothing further, or receive an undifferentiated newsletter.'),
  ('4.4', 1, 'One sequence for all non-converting contacts, unchanged for more than 12 months, reported on opens and clicks alone.'),
  ('4.4', 2, 'Multiple sequences exist, branched by form or campaign source rather than by behaviour. There is no re-engagement programme for dormant accounts or closed-lost, and contribution to pipeline is not measured.'),
  ('4.4', 3, 'Behaviour-triggered nurture is running with segmentation that reflects persona and stage, and closed-lost or dormant re-engagement exists. Contribution to qualified opportunity is not isolated and content is not refreshed on a cadence.'),
  ('4.4', 4, 'Always-on programmes are segmented by behaviour and stage, include closed-lost re-engagement, and their contribution to qualified opportunity is measured with content refreshed on evidence.'),
  ('4.4', 5, 'As level 4, and programmes are reviewed on a cadence with a named owner, suppression and consent governance is documented and adhered to in the configuration, and message content draws from the governed source.'),
  ('4.5', 0, 'No shared qualification definition. Marketing and sales describe a qualified lead differently in interview and neither can produce a written definition.'),
  ('4.5', 1, 'A written definition exists, authored by marketing. Sales does not use it, and Blend finds handed-over leads being rejected or ignored at a rate the client cannot state.'),
  ('4.5', 2, 'A jointly authored definition exists on paper. There is no service level for follow-up, no rejection loop, and acceptance rate is not measured. Interviews confirm sales works only a portion of what is handed over.'),
  ('4.5', 3, 'The definition is agreed by both functions with an acceptance and rejection process, and acceptance rate and response time are measured. The definition has not been tested against conversion outcomes and has not been revised inside 12 months.'),
  ('4.5', 4, 'The definition is agreed, instrumented, and tested against opportunity conversion, with a response-time service level the data shows is being met and a rejection loop that feeds back into scoring.'),
  ('4.5', 5, 'As level 4, and the definition is reviewed jointly on a defined cadence with a named owner, held in one place both functions and every system read from, and revised on conversion evidence.'),
  ('H04', 0, 'A name and contact details travel. No qualification rationale and no research history: Blend''s sample of recent handovers finds sales beginning discovery with questions the company already had answers to.'),
  ('H04', 1, 'Handover happens through the CRM with source and form data. Qualification reasoning is absent, and reps say in interview that they do not read what is attached.'),
  ('H04', 2, 'Qualification rationale is recorded on some handovers. The research trail exists in the marketing platform but is not present where the rep works, and no service level governs what must be attached.'),
  ('H04', 3, 'Rationale, research trail and known contacts all travel on the record. The rep assembles the picture manually, and Blend''s timing sample shows a delay between signal and first contact that the client had not measured.'),
  ('H04', 4, 'A complete handover including rationale, research history, buying group and likely trigger is present where the rep works, with response time measured against a stated target.'),
  ('H04', 5, 'As level 4, and the briefing is generated from the record automatically before first contact, with a named owner for the handover definition and a cadence for reviewing it against conversion evidence.'),
  ('5.1', 0, 'Stages exist as names only. No exit criteria are documented, and Blend finds open deals sitting in stages inconsistent with any recorded activity.'),
  ('5.1', 1, 'Stages are documented but describe seller activity rather than buyer commitment. There are no exit criteria, and Blend''s data review finds stage skipping on a material share of won deals.'),
  ('5.1', 2, 'Exit criteria are documented for some stages and not enforced: deals advance without the criteria being met, and the time-in-stage distribution shows a pattern the client cannot explain.'),
  ('5.1', 3, 'Exit criteria are documented for every stage and framed around buyer commitment. Enforcement is inconsistent by rep, and stage-to-stage conversion and time-in-stage are reported but not used to manage.'),
  ('5.1', 4, 'Exit criteria are enforced, evidenced by required fields or approvals in the CRM, with stage-to-stage conversion and time-in-stage reviewed and acted on. Variance between reps is visible and explicable.'),
  ('5.1', 5, 'As level 4, and the stage model is reviewed on a cadence against conversion and cycle-time evidence with a named owner, and changes propagate to enablement and forecasting without manual reconciliation.'),
  ('5.2', 0, 'No discovery framework. Blend''s sample of recorded calls or notes finds no consistent question set and no recorded qualification decision.'),
  ('5.2', 1, 'A discovery framework exists in training material. Sampled calls or notes show it is not used, and qualification rationale is absent from the record on most opportunities.'),
  ('5.2', 2, 'Discovery notes are captured against a template on most opportunities. The content is uneven: Blend''s sample finds the buyer''s decision process, timeline and success criteria recorded on a minority of them.'),
  ('5.2', 3, 'Discovery is consistent across most reps on the core areas and qualification rationale is recorded. Consistency has not been tested against outcome, and no coaching loop runs from call evidence.'),
  ('5.2', 4, 'Discovery consistency is evidenced in a sampled review, qualification rationale is recorded and used in deal review, and a coaching loop from call evidence is running with named ownership.'),
  ('5.2', 5, 'As level 4, and discovery output is structured on the record so it feeds downstream stages and tooling directly, reviewed on a cadence, with the question set revised on win/loss evidence.'),
  ('5.3', 0, 'No mutual action planning. The buyer''s internal process is not recorded on any opportunity Blend samples.'),
  ('5.3', 1, 'Reps ask about process informally. Nothing is documented or shared with the buyer, and Blend finds no record of approval steps, procurement or security review on won deals.'),
  ('5.3', 2, 'Some reps use a close plan of their own making. It is not shared with the buyer, not consistent between reps, and not visible in the CRM. Blocking personas appear late in most sampled deals.'),
  ('5.3', 3, 'A mutual action plan template exists and is used on larger deals and shared with the buyer. Use is inconsistent across segments, and plans are not maintained after creation.'),
  ('5.3', 4, 'Mutual action plans are in use across the deals where they matter, shared and maintained with the buyer, with buying group composition and approval path recorded on the opportunity.'),
  ('5.3', 5, 'As level 4, and the plan is generated from the deal record rather than assembled by hand, reviewed on a cadence, with buyer-facing material drawn from the governed proof and messaging source.'),
  ('5.4', 0, 'Proposals are authored from scratch each time with no template and no approval path, and contracting time cannot be measured.'),
  ('5.4', 1, 'A proposal template exists and content is heavily rewritten per deal. There are no standard commercial terms, legal review is triggered on discovery rather than anticipated, and elapsed time from discovery to proposal is not measured.'),
  ('5.4', 2, 'Templates and standard terms exist. Blend''s measurement of elapsed time from discovery to proposal in the client''s own records returns a duration the client had never quantified, and security and procurement requirements are handled reactively.'),
  ('5.4', 3, 'Standard terms, a defined approval path and a known median time from discovery to proposal are all in place. Security questionnaires and procurement requirements are anticipated for known account types but not for new ones.'),
  ('5.4', 4, 'Proposal production, approval and contracting are instrumented with measured elapsed times, with standard positions for common legal and security requirements and a defined path for each.'),
  ('5.4', 5, 'As level 4, and proposal and scope documents are generated from the deal record and the governed proof library, so elapsed time from discovery to a proposal in the buyer''s hands is measured in hours rather than days, reviewed on a cadence with a named owner.'),
  ('5.5', 0, 'No forecast process Blend can review, or a forecast with no retained history against which accuracy could be measured.'),
  ('5.5', 1, 'The forecast is produced by rep judgement and aggregated. No history is retained, so accuracy cannot be computed, and Blend''s hygiene check finds a material share of open pipeline carrying close dates in the past.'),
  ('5.5', 2, 'Forecast history exists for at least two quarters. Accuracy is computable by Blend and sits outside a band the client can explain. Hygiene rules exist without enforcement, and stale pipeline is present at a level that distorts coverage.'),
  ('5.5', 3, 'Forecast accuracy is tracked and reviewed and hygiene is enforced periodically. The forecast rests on stage probability rather than exit criteria or evidence, and coverage ratios are not set against measured conversion.'),
  ('5.5', 4, 'Forecast accuracy is tracked over four or more quarters inside a stated band, hygiene is enforced continuously, and coverage is set against measured stage conversion rather than a rule of thumb.'),
  ('5.5', 5, 'As level 4, and the forecast is derived from the same records management uses daily with no separate reconciliation, reviewed on a cadence with a named owner, and variance analysed by cause rather than by rep.'),
  ('H05', 0, 'Nothing structured travels. Blend''s read of recent onboardings finds delivery learning what was sold from the customer.'),
  ('H05', 1, 'A contract and an internal note travel. Commitments made in the sale that are not in the contract do not travel at all, and Blend finds at least one instance where that caused a reset with the customer.'),
  ('H05', 2, 'A handover document exists and is completed inconsistently. Success criteria and named stakeholders are absent from most, and nothing records what was promised beyond the written scope.'),
  ('H05', 3, 'Scope, commitments, success criteria and stakeholders travel on a structured record for most deals. Delivery still re-keys it into a separate plan, and completeness is not measured.'),
  ('H05', 4, 'A complete structured record travels for every closed-won deal, including commitments made outside the contract, and its completeness is measured with gaps returned to sales.'),
  ('H05', 5, 'As level 4, and the record becomes the delivery plan directly without re-entry, with a named owner for the handover definition and a cadence for reviewing it against retention outcomes.'),
  ('6.1', 0, 'Delivery has no defined intake. Blend''s read of recent onboardings finds the delivery team re-running discovery from scratch on the majority.'),
  ('6.1', 1, 'Intake happens through an internal kickoff with no standard agenda or checklist. What was sold is reconstructed verbally, and Blend finds a documented instance of a commitment surfacing after work began.'),
  ('6.1', 2, 'A handover checklist exists. Delivery accepts whatever arrives with no right of refusal, and no record is kept of gaps found at intake.'),
  ('6.1', 3, 'Structured intake with a defined checklist and a named receiver. Gaps found at intake are recorded but not returned to sales, and acceptance is not conditional on the record being complete.'),
  ('6.1', 4, 'Intake is structured, gaps are recorded and returned to sales, acceptance is conditional on completeness, and the rate of incomplete handovers is measured.'),
  ('6.1', 5, 'As level 4, and the signed scope translates into a delivery plan with owners and dates without manual re-entry, reviewed on a cadence with a named owner, with the incomplete-handover rate used to change sales practice.'),
  ('6.2', 0, 'No defined onboarding. Each implementation runs to the preference of whoever leads it, and first value is undefined.'),
  ('6.2', 1, 'An onboarding process exists as a task list. First value is not defined, so time-to-first-value cannot be computed, and duration varies widely with no explanation.'),
  ('6.2', 2, 'Onboarding is standardised by product or package. First value is defined loosely, usually as go-live or training completion rather than as an outcome the customer experiences.'),
  ('6.2', 3, 'A defined first-value moment exists and is tracked, and onboarding is designed backwards from it. It has not been tested against retention, and variation by cohort is not analysed.'),
  ('6.2', 4, 'Time-to-first-value is measured per customer, cohorted, and shown to correlate with retention. Onboarding has been revised on that evidence.'),
  ('6.2', 5, 'As level 4, and the plan is generated from the signed scope, first value is instrumented from usage or delivery data rather than reported by a person, and the design is reviewed on a cadence with a named owner.'),
  ('6.3', 0, 'No adoption or usage data reaches the customer-facing team.'),
  ('6.3', 1, 'Usage data exists but does not reach customer success. Account reviews rely on what the customer chooses to say.'),
  ('6.3', 2, 'Basic usage reporting reaches the team — logins, seats, volume — with no view of feature depth or of the behaviours associated with accounts that stay.'),
  ('6.3', 3, 'Adoption is tracked against a defined set of behaviours and visible per account. The behaviours were chosen by judgement and have not been tested against renewal outcomes.'),
  ('6.3', 4, 'The tracked behaviours are validated against renewal and expansion outcomes, adoption is visible per account and per cohort, and gaps drive a defined action.'),
  ('6.3', 5, 'As level 4, and adoption signals sit on the same record as commercial data with a named owner, reviewed on a cadence and revised as the product or service changes.'),
  ('6.4', 0, 'No health scoring. Risk becomes visible when a customer gives notice.'),
  ('6.4', 1, 'Health is a subjective status set by the account owner with no defined inputs, updated irregularly.'),
  ('6.4', 2, 'A health score exists with defined inputs. Blend''s retrospective test against accounts that churned shows it did not flag them ahead of notice, and no threshold triggers action.'),
  ('6.4', 3, 'Health score with defined inputs and a threshold that triggers a review. It has not been validated against actual churn, and the review does not reliably produce an action.'),
  ('6.4', 4, 'The score is validated against churn outcomes and revised on that evidence, thresholds trigger a defined play with an owner, and the lead time between flag and churn is measured.'),
  ('6.4', 5, 'As level 4, and signals are computed continuously from usage, support and sentiment on one record, with a named owner and a cadence for revising the model.'),
  ('6.5', 0, 'No escalation path. Recovery depends on who the customer happens to contact.'),
  ('6.5', 1, 'Escalation exists informally. There are no severity levels, no response commitments, and no record of what was escalated or how it resolved.'),
  ('6.5', 2, 'A documented escalation path with severity levels exists. Save motions are improvised per account and outcomes are not recorded, so nothing is learned across cases.'),
  ('6.5', 3, 'Escalation and save plays are defined and recorded. Save rate is computable by Blend but not tracked by the client, and root cause is not analysed across cases.'),
  ('6.5', 4, 'Escalations and saves are recorded with outcome and root cause, save rate is tracked, and recurring causes are fed to the function that owns them.'),
  ('6.5', 5, 'As level 4, and escalation triggers fire from monitored signals rather than from customer complaint, reviewed on a cadence with a named owner.'),
  ('H06', 0, 'Nothing travels. There is no record of value delivered, and proof is sourced by asking who might have a story.'),
  ('H06', 1, 'Value delivered is discussed in reviews and recorded nowhere retrievable. Case studies are reconstructed months later from memory.'),
  ('H06', 2, 'Some outcomes are recorded in narrative fields on the account. They are not quantified, not timestamped, and not visible to the team that produces proof.'),
  ('H06', 3, 'Quantified outcomes with a date are recorded for most accounts and are retrievable on request. Capture depends on a person remembering, and nothing signals that a story is available.'),
  ('H06', 4, 'Every delivered outcome is captured with the measure, the person who saw it and the date, visible to the team that turns it into proof without anyone having to ask.'),
  ('H06', 5, 'As level 4, and capture is triggered by detected success rather than by recall, feeding the proof engine directly, with a named owner and a cadence.'),
  ('7.1', 0, 'No structured voice-of-customer capture. What customers think sits in the heads of individual account owners.'),
  ('7.1', 1, 'Occasional surveys or review notes. Nothing is captured at the moment value is delivered, and there is no searchable record of customer outcomes.'),
  ('7.1', 2, 'Regular satisfaction measurement runs. Success moments are recorded ad hoc in narrative fields, and Blend cannot retrieve a list of quantified customer outcomes from the window.'),
  ('7.1', 3, 'Success signals are captured against a defined prompt in reviews and stored retrievably. Capture depends on a person remembering, and coverage across the base is uneven.'),
  ('7.1', 4, 'Success signals are captured systematically across the base, with the outcome quantified, the person who saw it named, and the date recorded.'),
  ('7.1', 5, 'As level 4, and signals are detected from usage, support sentiment and call content rather than waiting for someone to log them, held on one record with a named owner and a review cadence.'),
  ('7.2', 0, 'No case study production and no reference list.'),
  ('7.2', 1, 'Case studies are produced when marketing has capacity. Sourcing a reference means asking customer success who might say yes.'),
  ('7.2', 2, 'Case studies are produced as an annual or campaign-driven project. Reference availability is not tracked, and the same small group of customers carries every request.'),
  ('7.2', 3, 'A production cadence exists and a reference list is maintained. Coverage by segment is uneven, reference fatigue is unmanaged, and permissions are chased per request.'),
  ('7.2', 4, 'Production runs on a cadence against a coverage map by segment and persona, references are tracked with permission status and usage, and fatigue is managed by rotation.'),
  ('7.2', 5, 'As level 4, and production is triggered by captured success signals rather than by a content calendar, feeding the governed proof library that stage 02 draws from, with a named owner and a cadence.'),
  ('7.3', 0, 'No referral motion. Referrals happen and are not recorded as such.'),
  ('7.3', 1, 'Referrals are welcomed and never asked for. No source value distinguishes referred pipeline, so its contribution cannot be measured.'),
  ('7.3', 2, 'Referral source is recorded on some opportunities. Asking is left to individual judgement, there is no defined moment to ask, and no mechanic or incentive exists.'),
  ('7.3', 3, 'A defined referral ask exists with a mechanic that makes introductions easy, and referred pipeline is tracked. The ask is not tied to a success moment, and conversion is not compared against other sources.'),
  ('7.3', 4, 'Referral asks are made at defined moments, referred pipeline is tracked separately with conversion and value compared against other sources, and the mechanic is maintained.'),
  ('7.3', 5, 'As level 4, and the ask is triggered by a captured success signal in the week the value was felt, with a named owner and a review cadence.'),
  ('7.4', 0, 'No advocacy activity beyond individual relationships.'),
  ('7.4', 1, 'Customers occasionally appear in a webinar or a quote. Nothing is planned, and no record identifies who is willing to speak publicly.'),
  ('7.4', 2, 'Some customer-led content is produced. Advocacy depends on the same handful of relationships, and there is no programme, tiering or owner.'),
  ('7.4', 3, 'An advocacy programme exists with identified advocates and a content plan. Participation is not tracked to outcome, and community, where it exists, is unmanaged.'),
  ('7.4', 4, 'Advocacy runs as a programme with tiers, a maintained advocate list, planned customer-led content, and contribution to pipeline tracked.'),
  ('7.4', 5, 'As level 4, and advocate identification draws on captured success and sentiment signals rather than on who the team happens to know, with a named owner and a cadence.'),
  ('7.5', 0, 'No satisfaction measurement runs.'),
  ('7.5', 1, 'A survey runs and results are reported. No action is defined for any score, and Blend finds no instance of a response producing a follow-up.'),
  ('7.5', 2, 'Satisfaction is measured on a cadence and results are reviewed. Follow-up is discretionary and unrecorded, and detractor responses route nowhere specific.'),
  ('7.5', 3, 'Defined follow-up exists for detractors and promoters with an owner. Closure is not tracked, and satisfaction is not analysed against renewal or expansion outcomes.'),
  ('7.5', 4, 'Every response routes to a defined action with an owner and a closure record, and satisfaction is analysed against renewal and expansion outcomes.'),
  ('7.5', 5, 'As level 4, and responses trigger the action automatically on the same record as commercial and usage data, reviewed on a cadence with a named owner.'),
  ('H07', 0, 'Nothing travels. Satisfaction data and expansion activity have no connection to each other.'),
  ('H07', 1, 'Survey results are reported to the business. Nobody acts on a promoter response commercially, and Blend finds no expansion conversation traceable to one.'),
  ('H07', 2, 'Advocacy and satisfaction data are visible to account teams in a report. Acting on it depends on someone reading the report and deciding to.'),
  ('H07', 3, 'Strong satisfaction signals are flagged to account owners. The flag carries no context and no play, and there is no time expectation on acting.'),
  ('H07', 4, 'A specific opening travels with its context — which customer, about what, and which account team should act — with a time expectation and a recorded outcome.'),
  ('H07', 5, 'As level 4, and the opening arrives as a triggered task carrying its own context in the week the value was felt, with a named owner and a cadence for reviewing conversion.'),
  ('8.1', 0, 'No view of what customers own against what they could own.'),
  ('8.1', 1, 'Product or service ownership per account is retrievable, but no white space view exists. Opportunity is assessed from memory in an account review.'),
  ('8.1', 2, 'White space is mapped for the largest accounts in a spreadsheet maintained by hand, out of date, and not visible where the account team works.'),
  ('8.1', 3, 'White space is derivable for all accounts from the system of record. It is not valued, so it cannot be prioritised, and it is refreshed manually.'),
  ('8.1', 4, 'White space is mapped and valued for every account, visible where the account team works, and refreshed automatically from ownership data.'),
  ('8.1', 5, 'As level 4, and white space is prioritised by fit and propensity using renewal and expansion evidence, with a named owner and a review cadence.'),
  ('8.2', 0, 'No expansion triggers. Expansion happens when a customer asks, and Blend''s classification of expansion events in the window finds effectively all of them customer-initiated.'),
  ('8.2', 1, 'Account owners watch for opportunity informally. No signal is defined and nothing routes.'),
  ('8.2', 2, 'Some signals are named in a playbook — usage thresholds, headcount growth, contract events — and none is instrumented or routed.'),
  ('8.2', 3, 'At least one trigger is instrumented and routes to an owner. Triggers were chosen by judgement rather than derived from what preceded past expansions, and no response time is measured.'),
  ('8.2', 4, 'Triggers are derived from analysis of what actually preceded past expansions, instrumented, routed with an owner and a play, with response time measured.'),
  ('8.2', 5, 'As level 4, and triggers are computed continuously across usage, support and organisational signals on one record, reviewed and revised on outcome evidence with a named owner.'),
  ('8.3', 0, 'No defined plays. Expansion conversations are improvised.'),
  ('8.3', 1, 'Reps sell what they happen to know. No material supports a specific expansion path, and there is no view of which paths convert.'),
  ('8.3', 2, 'Generic expansion material exists. It is not differentiated by segment or by what the account already owns, and conversion by path is not measured.'),
  ('8.3', 3, 'Plays exist for the main expansion paths with supporting material. They are not differentiated by segment, and conversion is measured only in aggregate.'),
  ('8.3', 4, 'Plays are defined by segment and by current ownership, with conversion and value measured per play and material maintained.'),
  ('8.3', 5, 'As level 4, and play selection is driven by the trigger that fired, drawing on the governed proof library, reviewed on a cadence with a named owner.'),
  ('8.4', 0, 'Renewal is handled at expiry with no process, and gross retention is not separately reported.'),
  ('8.4', 1, 'Renewals are worked from a date list. Timing depends on who notices, and gross and net retention are conflated in reporting.'),
  ('8.4', 2, 'A renewal process with a defined start point exists. It begins close to expiry, gross retention is reported but not cohorted, and at-risk renewals are identified by account owner opinion.'),
  ('8.4', 3, 'Renewal runs as a timed process starting well before expiry, with gross retention cohorted. Risk identification is not connected to health scoring, and non-renewal reasons are not analysed.'),
  ('8.4', 4, 'Renewal is a timed process with defined stages connected to health scoring, and gross retention is cohorted with non-renewal reasons analysed and fed upstream.'),
  ('8.4', 5, 'As level 4, and the process runs from signals on the same record as usage and support, reviewed on a cadence with a named owner, with non-renewal reasons feeding stage 01.'),
  ('8.5', 0, 'No account planning, and no executive review of the customer base.'),
  ('8.5', 1, 'Account plans exist as documents for the largest accounts, written once and not revisited.'),
  ('8.5', 2, 'Account planning happens annually for a subset. Plans are static documents disconnected from the system of record, and executive review is ad hoc.'),
  ('8.5', 3, 'Account plans are maintained for the priority accounts on a cadence with executive review scheduled. Plans do not draw on white space, trigger or health data.'),
  ('8.5', 4, 'Planning covers the priority accounts on a defined cadence, draws on white space, health and trigger data, and executive review produces recorded decisions with owners.'),
  ('8.5', 5, 'As level 4, and plans are generated and refreshed from the record rather than authored by hand, with a named owner and a cadence tied to the commercial calendar.'),
  ('H08', 0, 'Nothing travels. Renewal, churn and expansion outcomes never reach the people who define who the company is for.'),
  ('H08', 1, 'Retention is reported to leadership as a figure. No characteristics of who expanded or churned travel with it, and the ICP is not revisited on that basis.'),
  ('H08', 2, 'Churn and expansion are analysed when the numbers look unusual. The analysis is requested rather than scheduled, and its conclusions do not reach targeting or qualification.'),
  ('H08', 3, 'Renewal and expansion evidence reaches an ICP or segment review irregularly. What predicted each outcome is not identified, so the review works from outcomes rather than causes.'),
  ('H08', 4, 'Renewal, churn and expansion evidence, including the predictors identified for each, is a scheduled input into ICP and segment review, with resulting changes recorded.'),
  ('H08', 5, 'As level 4, and the evidence flows into a governed ICP record on a defined cadence with a named owner, so targeting and qualification criteria are corrected by evidence several times a year.')
) as v(ref, level, descriptor)
join element e on e.ref = v.ref and e.instrument_version_id = '0f6a0006-0000-4000-8000-000000000006';
