-- 011 Seed: 7 interview guides, 115 questions, question-to-element mapping
--
-- Question-to-element mapping is authored at section level in Blend GEA_Interview
-- Question Map v0.1 and expanded to every question in the section, with per-question
-- overrides where the source guide names an element. Guide-level mapping alone was
-- too coarse for transcript synthesis and left H01, H02 and H06 with no link from
-- the element to the question that evidences it.

insert into interview_guide (instrument_version_id, ref, function_name,
  duration_minutes, preamble) values
  ('0f6a0006-0000-4000-8000-000000000006', 1, 'Executive sponsor', 60, 'CEO, CRO or whoever holds authority across marketing, sales and customer success.'),
  ('0f6a0006-0000-4000-8000-000000000006', 2, 'Marketing leadership', 60, 'CMO or VP Marketing.'),
  ('0f6a0006-0000-4000-8000-000000000006', 3, 'Sales leadership', 60, 'CRO or VP Sales.'),
  ('0f6a0006-0000-4000-8000-000000000006', 4, 'Revenue operations', 60, 'RevOps lead, or whoever actually owns the CRM.'),
  ('0f6a0006-0000-4000-8000-000000000006', 5, 'Customer success leadership', 60, 'VP Customer Success or equivalent.'),
  ('0f6a0006-0000-4000-8000-000000000006', 6, 'Finance', 60, 'CFO or Finance Director.'),
  ('0f6a0006-0000-4000-8000-000000000006', 7, 'Sales rep', 60, 'Two reps. Ideally one performing well and one performing around the average, so variance is visible.');

insert into interview_question (interview_guide_id, section_title,
  sort_order, question_text)
select g.id, v.section_title, v.sort_order, v.question_text from (values
  (1, 'Who you are for', 1, 'In one sentence, who is this company for? Ask for one sentence and let the pause happen.'),
  (1, 'Who you are for', 2, 'Who do you not serve? Push until the answer is specific rather than a size band.'),
  (1, 'Who you are for', 3, 'How did you arrive at that definition, and when was it last revisited?'),
  (1, 'Who you are for', 4, 'What in your own data would you point to as evidence for it?'),
  (1, 'Who you are for', 5, 'Show me where that definition lives. [Retrievability test for H01. Record what they actually produce.]'),
  (1, 'Why you win, and where you do not', 6, 'Why do your best customers choose you over the alternative they were actually considering?'),
  (1, 'Why you win, and where you do not', 7, 'Who is that alternative, most often?'),
  (1, 'Why you win, and where you do not', 8, 'Where do you consistently lose, and do you know why?'),
  (1, 'Why you win, and where you do not', 9, 'What would a competitor say about you that you would find hard to argue with?'),
  (1, 'Pricing and packaging', 10, 'When did the current packaging get set, and for what version of the business?'),
  (1, 'Pricing and packaging', 11, 'Who can approve a discount, and does that hold in practice?'),
  (1, 'The loop back', 12, 'What did last year’s renewals and churn teach you about who you are for?'),
  (1, 'The loop back', 13, 'Did anything change in targeting or qualification as a result? [H08. If yes, ask to see it.]'),
  (1, 'Scope and ownership', 14, 'If this assessment finds something uncomfortable about a function you are close to, what happens to that finding?'),
  (1, 'Scope and ownership', 15, 'Who else in the leadership team needs to own part of the outcome?'),
  (2, 'Narrative and message, first priority', 1, 'What is the core narrative, and where does it live? [Ask to see it.]'),
  (2, 'Narrative and message, first priority', 2, 'Who owns it, and when was it last changed? What triggered the change?'),
  (2, 'Narrative and message, first priority', 3, 'How many personas do you actively write for, and where does the persona definition come from?'),
  (2, 'Narrative and message, first priority', 4, 'How do you know what the buying group actually looks like on a deal you won?'),
  (2, 'Narrative and message, first priority', 5, 'Where does a campaign writer get an approved claim and the proof for it? [Retrievability test for H02.]'),
  (2, 'Narrative and message, first priority', 6, 'Where does whoever wrote your most recent outbound sequence get the approved message and the proof for it? [Retrievability test for H02. Ask to see the sequence and what they worked from.]'),
  (2, 'Proof', 7, 'How many current case studies carry a number the client has verified?'),
  (2, 'Proof', 8, 'If sales needs a reference in your strongest segment tomorrow, what happens?'),
  (2, 'Proof', 9, 'Who produces case studies, and on what trigger?'),
  (2, 'Channels', 10, 'Take me through why the budget is split the way it is.'),
  (2, 'Channels', 11, 'What job does each channel have? Ask channel by channel rather than in general.'),
  (2, 'Channels', 12, 'If paid stopped tomorrow, what reach would you still own?'),
  (2, 'Channels', 13, 'What do you know about how you show up in AI assistants? [Do not share the P12 result.]'),
  (2, 'Engagement', 14, 'What are the next steps on the site for someone six months from buying?'),
  (2, 'Engagement', 15, 'How does a signal become something sales acts on, and how fast?'),
  (2, 'Engagement', 16, 'What happens to a contact who does not convert?'),
  (2, 'Qualification, ask this even though sales will also be asked', 17, 'What is a qualified lead here? Ask for the definition in their words, not the document.'),
  (2, 'Qualification, ask this even though sales will also be asked', 18, 'What proportion does sales work, and how do you know?'),
  (2, 'Qualification, ask this even though sales will also be asked', 19, 'Where is that definition written, and who agreed it?'),
  (3, 'Pipeline and process', 1, 'Walk me through the stages. What has to be true for a deal to move out of each one?'),
  (3, 'Pipeline and process', 2, 'What stops a deal moving without that being true?'),
  (3, 'Pipeline and process', 3, 'Where do deals most often stall, and what is happening at that point?'),
  (3, 'Pipeline and process', 4, 'How much variance is there between your best and weakest reps, and what explains it?'),
  (3, 'Discovery and buyer process', 5, 'What does a rep have to establish on a first call, and where does it get recorded?'),
  (3, 'Discovery and buyer process', 6, 'On the last deal you won, who signed and who else had to agree?'),
  (3, 'Discovery and buyer process', 7, 'How do you find out about procurement or security review, and when?'),
  (3, 'Discovery and buyer process', 8, 'Do you build a plan with the buyer for their internal process? [Ask to see the last one.]'),
  (3, 'Proposal and contracting', 9, 'From the end of a discovery call, how long until the buyer has a proposal?'),
  (3, 'Proposal and contracting', 10, 'What is in that time? Ask them to account for it step by step.'),
  (3, 'Proposal and contracting', 11, 'What slows contracting most often?'),
  (3, 'Forecast', 12, 'How is the forecast built, and by whom?'),
  (3, 'Forecast', 13, 'When it is wrong, what is usually the cause?'),
  (3, 'Forecast', 14, 'What do you do about a deal with a close date in the past?'),
  (3, 'Qualification, and what arrives', 15, 'What is a qualified lead? Their definition, in their words.'),
  (3, 'Qualification, and what arrives', 16, 'What arrives with one, and is it enough to start a conversation?'),
  (3, 'Qualification, and what arrives', 17, 'What proportion do you work, and what happens to the rest?'),
  (4, 'What the data can and cannot carry', 1, 'Which fields in the CRM would you not trust for a board number, and why?'),
  (4, 'What the data can and cannot carry', 2, 'Which are filled in because a workflow requires it rather than because someone knows the answer?'),
  (4, 'What the data can and cannot carry', 3, 'Where do marketing, sales and customer success disagree about the same customer?'),
  (4, 'What the data can and cannot carry', 4, 'How much of your week is spent making two systems agree? [Direct input to the TCO reconciliation line.]'),
  (4, 'Signal, routing and handover', 5, 'Walk me through what happens between a form submission and a rep making contact.'),
  (4, 'Signal, routing and handover', 6, 'What is in the lead score, and who decided that?'),
  (4, 'Signal, routing and handover', 7, 'Has anyone tested whether the score predicts conversion?'),
  (4, 'Signal, routing and handover', 8, 'What information travels to the rep, and where does it appear for them? [H04.]'),
  (4, 'Signal, routing and handover', 9, 'What happens to the behaviour a contact showed before they filled in the form? [H03.]'),
  (4, 'Reporting and measurement', 10, 'Where does the number in the board pack come from, and how many steps are between the record and the slide?'),
  (4, 'Reporting and measurement', 11, 'Which reported metric would change if it were computed a different but equally reasonable way?'),
  (4, 'Stack', 12, 'List every system that holds customer data, including the spreadsheets.'),
  (4, 'Stack', 13, 'What integrations exist, what breaks, and how often?'),
  (4, 'Stack', 14, 'What was the last thing that broke after a vendor update?'),
  (4, 'Expansion and account data', 15, 'Can you tell me, from the system, what each account owns and what they could own?'),
  (4, 'Expansion and account data', 16, 'Is an expansion deal distinguishable from a new one in the data? [Critical for 8.2.]'),
  (5, 'What arrives from sales', 1, 'On the last customer you onboarded, how did you find out what had been sold? [H05.]'),
  (5, 'What arrives from sales', 2, 'Has a commitment ever surfaced after you started work? Tell me about the last time.'),
  (5, 'What arrives from sales', 3, 'Can you refuse a handover that is incomplete?'),
  (5, 'What arrives from sales', 4, 'Does the signed scope become the delivery plan, or do you rebuild it? [6.1.]'),
  (5, 'Onboarding and first value', 5, 'What is the moment a customer first gets value, specifically, and how do you know it happened?'),
  (5, 'Onboarding and first value', 6, 'How long does that take, typically? Ask whether that number is measured or estimated.'),
  (5, 'Onboarding and first value', 7, 'What makes an onboarding go badly?'),
  (5, 'Adoption and health', 8, 'What usage data do you see, and where?'),
  (5, 'Adoption and health', 9, 'How do you know an account is in trouble, and how far ahead?'),
  (5, 'Adoption and health', 10, 'Think of the last customer you lost. When did you know, and when could you have known?'),
  (5, 'Adoption and health', 11, 'What does a red health status actually trigger?'),
  (5, 'Capturing what customers say', 12, 'A customer tells you they hit a great result. What happens to that? [H06.]'),
  (5, 'Capturing what customers say', 13, 'Where would marketing find it six months later?'),
  (5, 'Capturing what customers say', 14, 'A customer scores you top marks in a survey. Who acts on that, and how? [H07.]'),
  (5, 'Renewal and expansion', 15, 'When does a renewal conversation start, relative to the renewal date?'),
  (5, 'Renewal and expansion', 16, 'How does expansion happen here? Push for whether the customer asked or the company noticed.'),
  (5, 'Renewal and expansion', 17, 'Give me the last three expansions and tell me which of those it was. [Direct evidence for 8.2.]'),
  (5, 'Renewal and expansion', 18, 'What is in an account plan, and when was the last one updated?'),
  (6, 'Cost of the stack', 1, 'What do you actually pay, annually, for each system that holds customer data?'),
  (6, 'Cost of the stack', 2, 'What did the integration between them cost to build, and what does it cost to keep running?'),
  (6, 'Cost of the stack', 3, 'How many people, or fractions of people, exist to make systems agree?'),
  (6, 'Cost of the stack', 4, 'What third-party services or contractors sit on top of that?'),
  (6, 'Cost of the stack', 5, 'Which of those costs buys a capability, and which exists because of how the stack was assembled?'),
  (6, 'Retention arithmetic', 6, 'How do you report gross and net retention, and are they reported separately?'),
  (6, 'Retention arithmetic', 7, 'Is retention cohorted, and by what?'),
  (6, 'Retention arithmetic', 8, 'What does a churn actually cost, in your numbers?'),
  (6, 'Pricing', 9, 'Do you see margin by package or product?'),
  (6, 'Pricing', 10, 'Has packaging ever changed because of what the margin analysis showed?'),
  (6, 'Pricing', 11, 'Where does realised pricing sit relative to list, and does that surprise you?'),
  (6, 'Forecast and confidence', 12, 'How much do you trust the sales forecast, and what do you do to it before it goes into the plan?'),
  (6, 'Forecast and confidence', 13, 'What is the biggest go-to-market spend you cannot connect to an outcome?'),
  (6, 'If sponsor-backed', 14, 'What does the sponsor ask for that takes you longest to produce?'),
  (6, 'If sponsor-backed', 15, 'Which growth assumption in the plan are you least confident the system can support?'),
  (7, 'The last deal you won', 1, 'Take me through it from first contact to signature.'),
  (7, 'The last deal you won', 2, 'What did you know about them before your first conversation, and where did you get it? [H04.]'),
  (7, 'The last deal you won', 3, 'What did you establish on that first call, and where did you write it down? [Ask to see it.]'),
  (7, 'The last deal you won', 4, 'Who else at their end had to agree, and when did you find out?'),
  (7, 'The last deal you won', 5, 'How long from that call to them having a proposal?'),
  (7, 'The last deal you lost', 6, 'What happened? Then: what did you record as the reason, and does that field capture it?'),
  (7, 'The last deal you lost', 7, 'Looking back, when did it actually go wrong?'),
  (7, 'What you use', 8, 'Show me the deck you used last week. [The point is whether it is the shared current one.]'),
  (7, 'What you use', 9, 'When you explain what the company does, what do you say? Listen for the approved core claim. [2.5.]'),
  (7, 'What you use', 10, 'Where do you get a proof point or a reference when you need one?'),
  (7, 'What you use', 11, 'What do you do that is not in the process, because the process does not work?'),
  (7, 'What arrives from marketing', 12, 'What does a marketing lead look like when it reaches you?'),
  (7, 'What arrives from marketing', 13, 'Do you work all of them? What makes you skip one?'),
  (7, 'What arrives from marketing', 14, 'What would make them more useful?'),
  (7, 'Handover onward', 15, 'After you close, what do you hand to delivery, and how? [H05.]'),
  (7, 'Handover onward', 16, 'Have you ever promised something that did not make it into the scope?')
) as v(guide_ref, section_title, sort_order, question_text)
join interview_guide g on g.ref = v.guide_ref and g.instrument_version_id = '0f6a0006-0000-4000-8000-000000000006';

insert into interview_question_element (interview_question_id, element_id)
select qq.id, e.id from (values
  (1, 1, '1.1'),
  (1, 1, '1.2'),
  (1, 2, '1.1'),
  (1, 2, '1.2'),
  (1, 3, '1.1'),
  (1, 3, '1.2'),
  (1, 4, '1.1'),
  (1, 4, '1.2'),
  (1, 5, '1.1'),
  (1, 5, '1.2'),
  (1, 5, 'H01'),
  (1, 6, '1.4'),
  (1, 7, '1.4'),
  (1, 8, '1.4'),
  (1, 9, '1.4'),
  (1, 10, '1.5'),
  (1, 11, '1.5'),
  (1, 12, 'H08'),
  (1, 13, 'H08'),
  (2, 1, '2.1'),
  (2, 1, '2.2'),
  (2, 2, '2.1'),
  (2, 2, '2.2'),
  (2, 3, '2.1'),
  (2, 3, '2.2'),
  (2, 3, 'H01'),
  (2, 4, '2.1'),
  (2, 4, '2.2'),
  (2, 5, '2.1'),
  (2, 5, '2.2'),
  (2, 5, 'H02'),
  (2, 6, '2.1'),
  (2, 6, '2.2'),
  (2, 6, 'H02'),
  (2, 7, '2.3'),
  (2, 8, '2.3'),
  (2, 9, '2.3'),
  (2, 10, '3.1'),
  (2, 10, '3.2'),
  (2, 10, '3.3'),
  (2, 10, '3.5'),
  (2, 11, '3.1'),
  (2, 11, '3.2'),
  (2, 11, '3.3'),
  (2, 11, '3.5'),
  (2, 12, '3.1'),
  (2, 12, '3.2'),
  (2, 12, '3.3'),
  (2, 12, '3.5'),
  (2, 13, '3.1'),
  (2, 13, '3.2'),
  (2, 13, '3.3'),
  (2, 13, '3.5'),
  (2, 14, '4.1'),
  (2, 14, '4.2'),
  (2, 14, '4.4'),
  (2, 15, '4.1'),
  (2, 15, '4.2'),
  (2, 15, '4.4'),
  (2, 16, '4.1'),
  (2, 16, '4.2'),
  (2, 16, '4.4'),
  (2, 17, '4.5'),
  (2, 18, '4.5'),
  (2, 19, '4.5'),
  (3, 1, '5.1'),
  (3, 2, '5.1'),
  (3, 3, '5.1'),
  (3, 4, '5.1'),
  (3, 5, '5.3'),
  (3, 6, '5.3'),
  (3, 7, '5.3'),
  (3, 8, '5.3'),
  (3, 9, '5.4'),
  (3, 10, '5.4'),
  (3, 11, '5.4'),
  (3, 12, '5.5'),
  (3, 13, '5.5'),
  (3, 14, '5.5'),
  (3, 15, '4.5'),
  (3, 15, 'H04'),
  (3, 16, '4.5'),
  (3, 16, 'H04'),
  (3, 17, '4.5'),
  (3, 17, 'H04'),
  (4, 5, '4.3'),
  (4, 5, 'H03'),
  (4, 5, 'H04'),
  (4, 6, '4.3'),
  (4, 6, 'H03'),
  (4, 6, 'H04'),
  (4, 7, '4.3'),
  (4, 7, 'H03'),
  (4, 7, 'H04'),
  (4, 8, '4.3'),
  (4, 8, 'H03'),
  (4, 8, 'H04'),
  (4, 9, '4.3'),
  (4, 9, 'H03'),
  (4, 9, 'H04'),
  (4, 10, '5.5'),
  (4, 11, '5.5'),
  (4, 15, '8.1'),
  (4, 15, '8.2'),
  (4, 16, '8.1'),
  (4, 16, '8.2'),
  (5, 1, '6.1'),
  (5, 1, 'H05'),
  (5, 2, '6.1'),
  (5, 2, 'H05'),
  (5, 3, '6.1'),
  (5, 3, 'H05'),
  (5, 4, '6.1'),
  (5, 4, 'H05'),
  (5, 5, '6.2'),
  (5, 6, '6.2'),
  (5, 7, '6.2'),
  (5, 8, '6.3'),
  (5, 8, '6.4'),
  (5, 8, '6.5'),
  (5, 9, '6.3'),
  (5, 9, '6.4'),
  (5, 9, '6.5'),
  (5, 10, '6.3'),
  (5, 10, '6.4'),
  (5, 10, '6.5'),
  (5, 11, '6.3'),
  (5, 11, '6.4'),
  (5, 11, '6.5'),
  (5, 12, '7.1'),
  (5, 12, '7.5'),
  (5, 12, 'H06'),
  (5, 12, 'H07'),
  (5, 13, '7.1'),
  (5, 13, '7.5'),
  (5, 13, 'H06'),
  (5, 13, 'H07'),
  (5, 14, '7.1'),
  (5, 14, '7.5'),
  (5, 14, 'H06'),
  (5, 14, 'H07'),
  (5, 15, '8.2'),
  (5, 15, '8.4'),
  (5, 15, '8.5'),
  (5, 16, '8.2'),
  (5, 16, '8.4'),
  (5, 16, '8.5'),
  (5, 17, '8.2'),
  (5, 17, '8.4'),
  (5, 17, '8.5'),
  (5, 18, '8.2'),
  (5, 18, '8.4'),
  (5, 18, '8.5'),
  (6, 6, '8.4'),
  (6, 7, '8.4'),
  (6, 8, '8.4'),
  (6, 9, '1.5'),
  (6, 10, '1.5'),
  (6, 11, '1.5'),
  (6, 12, '3.4'),
  (6, 12, '5.5'),
  (6, 13, '3.4'),
  (6, 13, '5.5'),
  (7, 1, '5.2'),
  (7, 1, '5.3'),
  (7, 1, '5.4'),
  (7, 1, 'H04'),
  (7, 2, '5.2'),
  (7, 2, '5.3'),
  (7, 2, '5.4'),
  (7, 2, 'H04'),
  (7, 3, '5.2'),
  (7, 3, '5.3'),
  (7, 3, '5.4'),
  (7, 3, 'H04'),
  (7, 4, '5.2'),
  (7, 4, '5.3'),
  (7, 4, '5.4'),
  (7, 4, 'H04'),
  (7, 5, '5.2'),
  (7, 5, '5.3'),
  (7, 5, '5.4'),
  (7, 5, 'H04'),
  (7, 6, '5.1'),
  (7, 7, '5.1'),
  (7, 8, '2.5'),
  (7, 9, '2.5'),
  (7, 10, '2.5'),
  (7, 11, '2.5'),
  (7, 12, '4.5'),
  (7, 12, 'H04'),
  (7, 13, '4.5'),
  (7, 13, 'H04'),
  (7, 14, '4.5'),
  (7, 14, 'H04'),
  (7, 15, 'H05'),
  (7, 16, 'H05')
) as v(guide_ref, sort_order, element_ref)
join interview_guide g on g.ref = v.guide_ref and g.instrument_version_id = '0f6a0006-0000-4000-8000-000000000006'
join interview_question qq on qq.interview_guide_id = g.id and qq.sort_order = v.sort_order
join element e on e.ref = v.element_ref and e.instrument_version_id = '0f6a0006-0000-4000-8000-000000000006';
