-- 012 Seed: 171 evidence requirements
--
-- Loaded from Blend GEA_Evidence Requirements v0.1. The source reference resolves to
-- one of three columns depending on the source kind: export line refs, an interview
-- guide, or an analysis key. Everything else leaves all three null.

insert into evidence_requirement (instrument_version_id, element_id, ref,
  source_kind, export_line_refs, interview_guide_id, analysis_key,
  description, is_mandatory, waiver_consequence)
select '0f6a0006-0000-4000-8000-000000000006', e.id, v.ref, v.source_kind::req_source_kind,
  v.export_line_refs, g.id, v.analysis_key, v.description,
  v.is_mandatory, v.waiver_consequence
from (values
  ('1.1', '1.1-R1', 'export', array['T1-01','T1-02','T1-07']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'An ICP that cannot be produced on request scores 0. Absence of closed-won firmographics is a Stage 1 data-quality flag and caps this element at 2 with confidence Low.'),
  ('1.1', '1.1-R2', 'analysis', null,
   null, 'icp_reconciliation', 'Accepted run of the icp reconciliation analysis',
   true, 'An ICP that cannot be produced on request scores 0. Absence of closed-won firmographics is a Stage 1 data-quality flag and caps this element at 2 with confidence Low.'),
  ('1.1', '1.1-R3', 'client_document', null,
   null, null, 'The current ICP document with author and date',
   true, 'An ICP that cannot be produced on request scores 0. Absence of closed-won firmographics is a Stage 1 data-quality flag and caps this element at 2 with confidence Low.'),
  ('1.1', '1.1-R4', 'interview', null,
   1, null, 'Accepted synthesis from the Executive sponsor session',
   true, 'An ICP that cannot be produced on request scores 0. Absence of closed-won firmographics is a Stage 1 data-quality flag and caps this element at 2 with confidence Low.'),
  ('1.2', '1.2-R1', 'export', array['T1-01','T1-02']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where segment is not a recorded field, note it as a finding, reconstruct segment from firmographics for the analysis, and cap at 3 with confidence Medium.'),
  ('1.2', '1.2-R2', 'analysis', null,
   null, 'icp_reconciliation', 'Accepted run of the icp reconciliation analysis',
   true, 'Where segment is not a recorded field, note it as a finding, reconstruct segment from firmographics for the analysis, and cap at 3 with confidence Medium.'),
  ('1.2', '1.2-R3', 'client_document', null,
   null, null, 'Current GTM or territory plan showing segment priority',
   true, 'Where segment is not a recorded field, note it as a finding, reconstruct segment from firmographics for the analysis, and cap at 3 with confidence Medium.'),
  ('1.2', '1.2-R4', 'interview', null,
   1, null, 'Accepted synthesis from the Executive sponsor session',
   true, 'Where segment is not a recorded field, note it as a finding, reconstruct segment from firmographics for the analysis, and cap at 3 with confidence Medium.'),
  ('1.3', '1.3-R1', 'export', array['T1-01','T1-07','T2-04']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where loss reason is absent or defaulted on more than half of records, that is the finding. Score no higher than 1 and record the defaulting rate in the report.'),
  ('1.3', '1.3-R2', 'analysis', null,
   null, 'win_loss_and_churn_patterns', 'Accepted run of the win loss and churn patterns analysis',
   true, 'Where loss reason is absent or defaulted on more than half of records, that is the finding. Score no higher than 1 and record the defaulting rate in the report.'),
  ('1.3', '1.3-R3', 'client_document', null,
   null, null, 'Two years of closed-won and closed-lost records including loss reason',
   true, 'Where loss reason is absent or defaulted on more than half of records, that is the finding. Score no higher than 1 and record the defaulting rate in the report.'),
  ('1.4', '1.4-R1', 'export', array['T1-01','T2-04']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Score on the material and data available. Where no competitor field is recorded, note it and use closed-lost narrative fields, at confidence Medium.'),
  ('1.4', '1.4-R2', 'client_document', null,
   null, null, 'Current differentiation or battlecard material with review date',
   true, 'Score on the material and data available. Where no competitor field is recorded, note it and use closed-lost narrative fields, at confidence Medium.'),
  ('1.4', '1.4-R3', 'public_surface', null,
   null, null, 'Substitution test on each competitive claim, against captured surfaces',
   true, 'Score on the material and data available. Where no competitor field is recorded, note it and use closed-lost narrative fields, at confidence Medium.'),
  ('1.4', '1.4-R4', 'interview', null,
   1, null, 'Accepted synthesis from the Executive sponsor session',
   true, 'Score on the material and data available. Where no competitor field is recorded, note it and use closed-lost narrative fields, at confidence Medium.'),
  ('1.4', '1.4-R5', 'interview', null,
   3, null, 'Accepted synthesis from the Sales leadership session',
   true, 'Score on the material and data available. Where no competitor field is recorded, note it and use closed-lost narrative fields, at confidence Medium.'),
  ('1.5', '1.5-R1', 'export', array['T1-01','T1-04']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where realised pricing is not recoverable from the CRM, request it from finance. If neither source holds it, that is a material finding: score no higher than 1.'),
  ('1.5', '1.5-R2', 'analysis', null,
   null, 'price_discount_dispersion', 'Accepted run of the price discount dispersion analysis',
   true, 'Where realised pricing is not recoverable from the CRM, request it from finance. If neither source holds it, that is a material finding: score no higher than 1.'),
  ('1.5', '1.5-R3', 'client_document', null,
   null, null, 'Current price book and discount authority policy',
   true, 'Where realised pricing is not recoverable from the CRM, request it from finance. If neither source holds it, that is a material finding: score no higher than 1.'),
  ('1.5', '1.5-R4', 'interview', null,
   1, null, 'Accepted synthesis from the Executive sponsor session',
   true, 'Where realised pricing is not recoverable from the CRM, request it from finance. If neither source holds it, that is a material finding: score no higher than 1.'),
  ('1.5', '1.5-R5', 'interview', null,
   6, null, 'Accepted synthesis from the Finance session',
   true, 'Where realised pricing is not recoverable from the CRM, request it from finance. If neither source holds it, that is a material finding: score no higher than 1.'),
  ('H01', 'H01-R1', 'observation', null,
   null, null, 'Current persona message set, requested from its author',
   true, 'A handoff is assessed by asking both sides what travels. Both sides are always available, so NE does not apply.'),
  ('H01', 'H01-R2', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'A handoff is assessed by asking both sides what travels. Both sides are always available, so NE does not apply.'),
  ('2.1', '2.1-R1', 'client_document', null,
   null, null, 'The current positioning or narrative document with owner and review date',
   true, 'Absence of a written narrative is scoreable at 0 without further evidence, provided interviews confirm no authoritative source exists.'),
  ('2.1', '2.1-R2', 'public_surface', null,
   null, null, 'Live asset comparison against the stated narrative, against captured surfaces',
   true, 'Absence of a written narrative is scoreable at 0 without further evidence, provided interviews confirm no authoritative source exists.'),
  ('2.1', '2.1-R3', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Absence of a written narrative is scoreable at 0 without further evidence, provided interviews confirm no authoritative source exists.'),
  ('2.2', '2.2-R1', 'export', array['T1-03','T1-08']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where contact roles are not populated, reconstruct the buying group from engagement history or interview, note the limitation, and cap at 3.'),
  ('2.2', '2.2-R2', 'client_document', null,
   null, null, 'Persona definitions with pains and goals',
   true, 'Where contact roles are not populated, reconstruct the buying group from engagement history or interview, note the limitation, and cap at 3.'),
  ('2.2', '2.2-R3', 'public_surface', null,
   null, null, 'Live asset audit across persona-facing surfaces',
   true, 'Where contact roles are not populated, reconstruct the buying group from engagement history or interview, note the limitation, and cap at 3.'),
  ('2.2', '2.2-R4', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Where contact roles are not populated, reconstruct the buying group from engagement history or interview, note the limitation, and cap at 3.'),
  ('2.3', '2.3-R1', 'export', array['T3-07']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Proof either exists and is inspectable or it does not. NE does not apply to this element.'),
  ('2.3', '2.3-R2', 'client_document', null,
   null, null, 'All current case studies with date and whether outcomes are quantified and client-verified',
   true, 'Proof either exists and is inspectable or it does not. NE does not apply to this element.'),
  ('2.3', '2.3-R3', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Proof either exists and is inspectable or it does not. NE does not apply to this element.'),
  ('2.4', '2.4-R1', 'public_surface', null,
   null, null, 'Owned and unowned surface audit, captured at audit time',
   true, 'Blend can always audit public surfaces without client input, so NE does not apply. Score what is publicly visible.'),
  ('2.4', '2.4-R2', 'external_upload', null,
   null, null, 'Answer engine spot-check results, run externally and uploaded',
   false, 'Blend can always audit public surfaces without client input, so NE does not apply. Score what is publicly visible.'),
  ('2.4', '2.4-R3', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Blend can always audit public surfaces without client input, so NE does not apply. Score what is publicly visible.'),
  ('2.5', '2.5-R1', 'export', array['T2-03','T2-04']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Work down the evidence ladder on the Sampling and Evidence Standard sheet and apply the cap it states for the tier reached.'),
  ('2.5', '2.5-R2', 'analysis', null,
   null, 'discovery_consistency_classification', 'Accepted run of the discovery consistency classification analysis',
   true, 'Work down the evidence ladder on the Sampling and Evidence Standard sheet and apply the cap it states for the tier reached.'),
  ('2.5', '2.5-R3', 'interview', null,
   7, null, 'Accepted synthesis from the Sales rep (run twice) session',
   true, 'Work down the evidence ladder on the Sampling and Evidence Standard sheet and apply the cap it states for the tier reached.'),
  ('H02', 'H02-R1', 'observation', null,
   null, null, 'Current approved proof assets for active channels, requested from their authors',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply.'),
  ('H02', 'H02-R2', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply.'),
  ('3.1', '3.1-R1', 'export', array['T3-01','T1-01']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where source or campaign attribution is absent on opportunities, cost per qualified opportunity cannot be computed. Cap at 2, confidence Low, and raise it as a Stage 1 data-quality flag.'),
  ('3.1', '3.1-R2', 'analysis', null,
   null, 'cost_per_qualified_opportunity', 'Accepted run of the cost per qualified opportunity analysis',
   true, 'Where source or campaign attribution is absent on opportunities, cost per qualified opportunity cannot be computed. Cap at 2, confidence Low, and raise it as a Stage 1 data-quality flag.'),
  ('3.1', '3.1-R3', 'client_document', null,
   null, null, '12 to 24 months of spend by channel and activity, budgeted and actual',
   true, 'Where source or campaign attribution is absent on opportunities, cost per qualified opportunity cannot be computed. Cap at 2, confidence Low, and raise it as a Stage 1 data-quality flag.'),
  ('3.1', '3.1-R4', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Where source or campaign attribution is absent on opportunities, cost per qualified opportunity cannot be computed. Cap at 2, confidence Low, and raise it as a Stage 1 data-quality flag.'),
  ('3.1', '3.1-R5', 'interview', null,
   4, null, 'Accepted synthesis from the Revenue operations session',
   true, 'Where source or campaign attribution is absent on opportunities, cost per qualified opportunity cannot be computed. Cap at 2, confidence Low, and raise it as a Stage 1 data-quality flag.'),
  ('3.2', '3.2-R1', 'export', array['T3-02','T3-03']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Blend can audit a public site without client input, so NE does not apply to the technical and architectural components.'),
  ('3.2', '3.2-R2', 'public_surface', null,
   null, null, 'Technical audit and content inventory against the segment priority from 1.2',
   true, 'Blend can audit a public site without client input, so NE does not apply to the technical and architectural components.'),
  ('3.2', '3.2-R3', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Blend can audit a public site without client input, so NE does not apply to the technical and architectural components.'),
  ('3.3', '3.3-R1', 'external_upload', null,
   null, null, 'Answer engine test results, run externally and uploaded',
   true, 'Blend runs this test independently, so NE does not apply. The prompt set used must be recorded in the report so the test is repeatable at re-score.'),
  ('3.3', '3.3-R2', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Blend runs this test independently, so NE does not apply. The prompt set used must be recorded in the report so the test is repeatable at re-score.'),
  ('3.4', '3.4-R1', 'export', array['T3-01','T1-01']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where the client runs no paid media at all, mark NE and state the reason. This is one of the few legitimate NE cases in the instrument.'),
  ('3.4', '3.4-R2', 'analysis', null,
   null, 'cost_per_qualified_opportunity', 'Accepted run of the cost per qualified opportunity analysis',
   true, 'Where the client runs no paid media at all, mark NE and state the reason. This is one of the few legitimate NE cases in the instrument.'),
  ('3.4', '3.4-R3', 'client_document', null,
   null, null, 'Paid spend by channel and campaign, 12 to 24 months',
   true, 'Where the client runs no paid media at all, mark NE and state the reason. This is one of the few legitimate NE cases in the instrument.'),
  ('3.4', '3.4-R4', 'interview', null,
   4, null, 'Accepted synthesis from the Revenue operations session',
   true, 'Where the client runs no paid media at all, mark NE and state the reason. This is one of the few legitimate NE cases in the instrument.'),
  ('3.4', '3.4-R5', 'interview', null,
   6, null, 'Accepted synthesis from the Finance session',
   true, 'Where the client runs no paid media at all, mark NE and state the reason. This is one of the few legitimate NE cases in the instrument.'),
  ('3.5', '3.5-R1', 'export', array['T1-01','T3-01']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where the client has no partner or event activity, mark NE with the reason. Where activity exists but is untracked, that is a finding rather than NE.'),
  ('3.5', '3.5-R2', 'client_document', null,
   null, null, 'Event and partner activity for 12 to 24 months with cost',
   true, 'Where the client has no partner or event activity, mark NE with the reason. Where activity exists but is untracked, that is a finding rather than NE.'),
  ('3.5', '3.5-R3', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Where the client has no partner or event activity, mark NE with the reason. Where activity exists but is untracked, that is a finding rather than NE.'),
  ('H03', 'H03-R1', 'export', array['T1-03','T2-02','T2-03']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply.'),
  ('H03', 'H03-R2', 'analysis', null,
   null, 'signal_to_first_contact', 'Accepted run of the signal to first contact analysis',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply.'),
  ('H03', 'H03-R3', 'interview', null,
   4, null, 'Accepted synthesis from the Revenue operations session',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply.'),
  ('4.1', '4.1-R1', 'export', array['T3-02','T1-01']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where submission-to-opportunity cannot be traced because form submissions do not create CRM records, cap at 2 and raise the tracking gap as a finding.'),
  ('4.1', '4.1-R2', 'analysis', null,
   null, 'signal_to_first_contact', 'Accepted run of the signal to first contact analysis',
   true, 'Where submission-to-opportunity cannot be traced because form submissions do not create CRM records, cap at 2 and raise the tracking gap as a finding.'),
  ('4.1', '4.1-R3', 'client_document', null,
   null, null, 'Full journey audit of the primary paths',
   true, 'Where submission-to-opportunity cannot be traced because form submissions do not create CRM records, cap at 2 and raise the tracking gap as a finding.'),
  ('4.1', '4.1-R4', 'public_surface', null,
   null, null, 'Journey audit across the conversion path',
   true, 'Where submission-to-opportunity cannot be traced because form submissions do not create CRM records, cap at 2 and raise the tracking gap as a finding.'),
  ('4.1', '4.1-R5', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Where submission-to-opportunity cannot be traced because form submissions do not create CRM records, cap at 2 and raise the tracking gap as a finding.'),
  ('4.2', '4.2-R1', 'export', array['T3-02','T3-03']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where consumption history is not retained beyond a short window, note the limitation, score on the inventory and mapping alone, and cap confidence at Medium.'),
  ('4.2', '4.2-R2', 'client_document', null,
   null, null, 'Content inventory with stage and persona tagging if it exists',
   true, 'Where consumption history is not retained beyond a short window, note the limitation, score on the inventory and mapping alone, and cap confidence at Medium.'),
  ('4.2', '4.2-R3', 'public_surface', null,
   null, null, 'Content inventory across the research journey',
   true, 'Where consumption history is not retained beyond a short window, note the limitation, score on the inventory and mapping alone, and cap confidence at Medium.'),
  ('4.2', '4.2-R4', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Where consumption history is not retained beyond a short window, note the limitation, score on the inventory and mapping alone, and cap confidence at Medium.'),
  ('4.3', '4.3-R1', 'export', array['T2-02','T2-03','T1-03']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where timestamps do not support a response-time calculation, that absence is a finding. Cap at 2.'),
  ('4.3', '4.3-R2', 'analysis', null,
   null, 'signal_to_first_contact', 'Accepted run of the signal to first contact analysis',
   true, 'Where timestamps do not support a response-time calculation, that absence is a finding. Cap at 2.'),
  ('4.3', '4.3-R3', 'interview', null,
   4, null, 'Accepted synthesis from the Revenue operations session',
   true, 'Where timestamps do not support a response-time calculation, that absence is a finding. Cap at 2.'),
  ('4.4', '4.4-R1', 'export', array['T3-04']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Programmes either exist in the platform and are inspectable or they do not, so NE does not apply.'),
  ('4.4', '4.4-R2', 'client_document', null,
   null, null, 'All active nurture and re-engagement programmes with their entry criteria, branching logic and last content refresh date',
   true, 'Programmes either exist in the platform and are inspectable or they do not, so NE does not apply.'),
  ('4.4', '4.4-R3', 'interview', null,
   2, null, 'Accepted synthesis from the Marketing leadership session',
   true, 'Programmes either exist in the platform and are inspectable or they do not, so NE does not apply.'),
  ('4.5', '4.5-R1', 'export', array['T1-01','T2-02']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Interview both functions separately before comparing. A definition that exists on paper but produces different verbal answers from the two functions scores no higher than 2.'),
  ('4.5', '4.5-R2', 'client_document', null,
   null, null, 'The written qualification definition, its author and date',
   true, 'Interview both functions separately before comparing. A definition that exists on paper but produces different verbal answers from the two functions scores no higher than 2.'),
  ('4.5', '4.5-R3', 'interview', null,
   3, null, 'Accepted synthesis from the Sales leadership session',
   true, 'Interview both functions separately before comparing. A definition that exists on paper but produces different verbal answers from the two functions scores no higher than 2.'),
  ('4.5', '4.5-R4', 'interview', null,
   4, null, 'Accepted synthesis from the Revenue operations session',
   true, 'Interview both functions separately before comparing. A definition that exists on paper but produces different verbal answers from the two functions scores no higher than 2.'),
  ('4.5', '4.5-R5', 'interview', null,
   7, null, 'Accepted synthesis from the Sales rep (run twice) session',
   true, 'Interview both functions separately before comparing. A definition that exists on paper but produces different verbal answers from the two functions scores no higher than 2.'),
  ('H04', 'H04-R1', 'export', array['T1-01','T2-01','T2-02','T2-03']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'This is the join where the largest volume is lost, so read the records rather than rely on process description. Interview at least two receiving reps directly.'),
  ('H04', 'H04-R2', 'analysis', null,
   null, 'handover_completeness_census', 'Accepted run of the handover completeness census analysis',
   true, 'This is the join where the largest volume is lost, so read the records rather than rely on process description. Interview at least two receiving reps directly.'),
  ('H04', 'H04-R3', 'interview', null,
   3, null, 'Accepted synthesis from the Sales leadership session',
   true, 'This is the join where the largest volume is lost, so read the records rather than rely on process description. Interview at least two receiving reps directly.'),
  ('H04', 'H04-R4', 'interview', null,
   4, null, 'Accepted synthesis from the Revenue operations session',
   true, 'This is the join where the largest volume is lost, so read the records rather than rely on process description. Interview at least two receiving reps directly.'),
  ('H04', 'H04-R5', 'interview', null,
   7, null, 'Accepted synthesis from the Sales rep (run twice) session',
   true, 'This is the join where the largest volume is lost, so read the records rather than rely on process description. Interview at least two receiving reps directly.'),
  ('5.1', '5.1-R1', 'export', array['T1-01','T2-01']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where stage history is not retained, note it, score on definitions and current pipeline only, and cap at 3 with confidence Low.'),
  ('5.1', '5.1-R2', 'analysis', null,
   null, 'stage_conversion_and_duration', 'Accepted run of the stage conversion and duration analysis',
   true, 'Where stage history is not retained, note it, score on definitions and current pipeline only, and cap at 3 with confidence Low.'),
  ('5.1', '5.1-R3', 'client_document', null,
   null, null, 'Stage definitions and documented exit criteria',
   true, 'Where stage history is not retained, note it, score on definitions and current pipeline only, and cap at 3 with confidence Low.'),
  ('5.1', '5.1-R4', 'interview', null,
   3, null, 'Accepted synthesis from the Sales leadership session',
   true, 'Where stage history is not retained, note it, score on definitions and current pipeline only, and cap at 3 with confidence Low.'),
  ('5.1', '5.1-R5', 'interview', null,
   4, null, 'Accepted synthesis from the Revenue operations session',
   true, 'Where stage history is not retained, note it, score on definitions and current pipeline only, and cap at 3 with confidence Low.'),
  ('5.1', '5.1-R6', 'interview', null,
   7, null, 'Accepted synthesis from the Sales rep (run twice) session',
   true, 'Where stage history is not retained, note it, score on definitions and current pipeline only, and cap at 3 with confidence Low.'),
  ('5.2', '5.2-R1', 'export', array['T2-03','T2-04']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Work down the evidence ladder on the Sampling and Evidence Standard sheet. Hand-score the validation set before trusting any classified rate.'),
  ('5.2', '5.2-R2', 'analysis', null,
   null, 'discovery_consistency_classification', 'Accepted run of the discovery consistency classification analysis',
   true, 'Work down the evidence ladder on the Sampling and Evidence Standard sheet. Hand-score the validation set before trusting any classified rate.'),
  ('5.2', '5.2-R3', 'client_document', null,
   null, null, 'Discovery notes on every closed opportunity in the window, and call transcripts for all of them where recording exists, read for whether decision process, timeline and success criteria are recorded',
   true, 'Work down the evidence ladder on the Sampling and Evidence Standard sheet. Hand-score the validation set before trusting any classified rate.'),
  ('5.2', '5.2-R4', 'interview', null,
   7, null, 'Accepted synthesis from the Sales rep (run twice) session',
   true, 'Work down the evidence ladder on the Sampling and Evidence Standard sheet. Hand-score the validation set before trusting any classified rate.'),
  ('5.3', '5.3-R1', 'export', array['T1-01','T1-08','T2-04']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Absence of a recorded buying group on the majority of sampled won deals caps this element at 2, regardless of any template in use.'),
  ('5.3', '5.3-R2', 'analysis', null,
   null, 'buying_group_composition', 'Accepted run of the buying group composition analysis',
   true, 'Absence of a recorded buying group on the majority of sampled won deals caps this element at 2, regardless of any template in use.'),
  ('5.3', '5.3-R3', 'client_document', null,
   null, null, 'Every closed opportunity in the window examined for recorded buying group, approval path, procurement and security requirements',
   true, 'Absence of a recorded buying group on the majority of sampled won deals caps this element at 2, regardless of any template in use.'),
  ('5.3', '5.3-R4', 'interview', null,
   3, null, 'Accepted synthesis from the Sales leadership session',
   true, 'Absence of a recorded buying group on the majority of sampled won deals caps this element at 2, regardless of any template in use.'),
  ('5.3', '5.3-R5', 'interview', null,
   7, null, 'Accepted synthesis from the Sales rep (run twice) session',
   true, 'Absence of a recorded buying group on the majority of sampled won deals caps this element at 2, regardless of any template in use.'),
  ('5.4', '5.4-R1', 'export', array['T1-05','T2-03']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where proposal issue dates are not recorded, reconstruct from document or email timestamps across the window, state the method, and cap confidence at Medium.'),
  ('5.4', '5.4-R2', 'client_document', null,
   null, null, 'Proposal and contract templates',
   true, 'Where proposal issue dates are not recorded, reconstruct from document or email timestamps across the window, state the method, and cap confidence at Medium.'),
  ('5.4', '5.4-R3', 'interview', null,
   7, null, 'Accepted synthesis from the Sales rep (run twice) session',
   true, 'Where proposal issue dates are not recorded, reconstruct from document or email timestamps across the window, state the method, and cap confidence at Medium.'),
  ('5.5', '5.5-R1', 'export', array['T3-08','T1-01','T2-01']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where no forecast history is retained, accuracy cannot be computed. Score no higher than 1 and state that the absence of retained forecast history is itself the finding.'),
  ('5.5', '5.5-R2', 'analysis', null,
   null, 'forecast_accuracy', 'Accepted run of the forecast accuracy analysis',
   true, 'Where no forecast history is retained, accuracy cannot be computed. Score no higher than 1 and state that the absence of retained forecast history is itself the finding.'),
  ('5.5', '5.5-R3', 'client_document', null,
   null, null, 'Forecast submissions for the last four quarters and the actual outcome of each',
   true, 'Where no forecast history is retained, accuracy cannot be computed. Score no higher than 1 and state that the absence of retained forecast history is itself the finding.'),
  ('5.5', '5.5-R4', 'interview', null,
   3, null, 'Accepted synthesis from the Sales leadership session',
   true, 'Where no forecast history is retained, accuracy cannot be computed. Score no higher than 1 and state that the absence of retained forecast history is itself the finding.'),
  ('5.5', '5.5-R5', 'interview', null,
   4, null, 'Accepted synthesis from the Revenue operations session',
   true, 'Where no forecast history is retained, accuracy cannot be computed. Score no higher than 1 and state that the absence of retained forecast history is itself the finding.'),
  ('5.5', '5.5-R6', 'interview', null,
   6, null, 'Accepted synthesis from the Finance session',
   true, 'Where no forecast history is retained, accuracy cannot be computed. Score no higher than 1 and state that the absence of retained forecast history is itself the finding.'),
  ('H05', 'H05-R1', 'export', array['T1-01','T1-07','T3-05']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply. Where no handover artefact exists at all, that is a level 0 finding rather than NE.'),
  ('H05', 'H05-R2', 'analysis', null,
   null, 'handover_completeness_census', 'Accepted run of the handover completeness census analysis',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply. Where no handover artefact exists at all, that is a level 0 finding rather than NE.'),
  ('H05', 'H05-R3', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply. Where no handover artefact exists at all, that is a level 0 finding rather than NE.'),
  ('H05', 'H05-R4', 'interview', null,
   7, null, 'Accepted synthesis from the Sales rep (run twice) session',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply. Where no handover artefact exists at all, that is a level 0 finding rather than NE.'),
  ('6.1', '6.1-R1', 'export', array['T1-07','T3-05','T1-01']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where no intake artefact exists, score on the onboarding record and interview and cap confidence at Medium.'),
  ('6.1', '6.1-R2', 'analysis', null,
   null, 'handover_completeness_census', 'Accepted run of the handover completeness census analysis',
   true, 'Where no intake artefact exists, score on the onboarding record and interview and cap confidence at Medium.'),
  ('6.1', '6.1-R3', 'client_document', null,
   null, null, 'Delivery intake process and checklist',
   true, 'Where no intake artefact exists, score on the onboarding record and interview and cap confidence at Medium.'),
  ('6.1', '6.1-R4', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'Where no intake artefact exists, score on the onboarding record and interview and cap confidence at Medium.'),
  ('6.2', '6.2-R1', 'export', array['T1-07','T3-05']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where first value is undefined, duration cannot be computed against it. Score no higher than 1 and report the absence of a definition as the finding.'),
  ('6.2', '6.2-R2', 'analysis', null,
   null, 'renewal_timing_and_reason', 'Accepted run of the renewal timing and reason analysis',
   true, 'Where first value is undefined, duration cannot be computed against it. Score no higher than 1 and report the absence of a definition as the finding.'),
  ('6.2', '6.2-R3', 'client_document', null,
   null, null, 'The definition of first value, if one exists, and how it is measured',
   true, 'Where first value is undefined, duration cannot be computed against it. Score no higher than 1 and report the absence of a definition as the finding.'),
  ('6.2', '6.2-R4', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'Where first value is undefined, duration cannot be computed against it. Score no higher than 1 and report the absence of a definition as the finding.'),
  ('6.3', '6.3-R1', 'export', array['T3-05']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'For a tech-enabled services business with no product telemetry, substitute delivery milestone and engagement data and state the substitution. NE does not apply.'),
  ('6.3', '6.3-R2', 'interview', null,
   4, null, 'Accepted synthesis from the Revenue operations session',
   true, 'For a tech-enabled services business with no product telemetry, substitute delivery milestone and engagement data and state the substitution. NE does not apply.'),
  ('6.3', '6.3-R3', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'For a tech-enabled services business with no product telemetry, substitute delivery milestone and engagement data and state the substitution. NE does not apply.'),
  ('6.4', '6.4-R1', 'export', array['T2-05','T1-07']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where historic health status is not retained, the score cannot be tested. Cap at 2, confidence Low, and record the retention gap as a finding.'),
  ('6.4', '6.4-R2', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'Where historic health status is not retained, the score cannot be tested. Cap at 2, confidence Low, and record the retention gap as a finding.'),
  ('6.5', '6.5-R1', 'export', array['T1-06']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where escalations are not recorded as a distinct object, reconstruct from support tickets and account notes, state the method, and cap confidence at Medium.'),
  ('6.5', '6.5-R2', 'client_document', null,
   null, null, 'Escalation path and severity definitions',
   true, 'Where escalations are not recorded as a distinct object, reconstruct from support tickets and account notes, state the method, and cap confidence at Medium.'),
  ('6.5', '6.5-R3', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'Where escalations are not recorded as a distinct object, reconstruct from support tickets and account notes, state the method, and cap confidence at Medium.'),
  ('H06', 'H06-R1', 'export', array['T1-07','T3-06']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply.'),
  ('H06', 'H06-R2', 'observation', null,
   null, null, 'A recent captured proof point, requested from the customer success owner',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply.'),
  ('H06', 'H06-R3', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply.'),
  ('7.1', '7.1-R1', 'export', array['T3-06','T2-04']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Coverage is measured against the whole customer base, not against the accounts that happen to have a record. Report the proportion.'),
  ('7.1', '7.1-R2', 'client_document', null,
   null, null, 'All voice-of-customer mechanisms and their cadence',
   true, 'Coverage is measured against the whole customer base, not against the accounts that happen to have a record. Report the proportion.'),
  ('7.1', '7.1-R3', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'Coverage is measured against the whole customer base, not against the accounts that happen to have a record. Report the proportion.'),
  ('7.2', '7.2-R1', 'export', array['T3-07']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Proof either exists and is inspectable or it does not, so NE does not apply.'),
  ('7.2', '7.2-R2', 'client_document', null,
   null, null, 'All case studies with date, segment and whether outcomes are quantified',
   true, 'Proof either exists and is inspectable or it does not, so NE does not apply.'),
  ('7.2', '7.2-R3', 'public_surface', null,
   null, null, 'Full reference and case study inventory',
   true, 'Proof either exists and is inspectable or it does not, so NE does not apply.'),
  ('7.3', '7.3-R1', 'export', array['T1-01']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where referral is not a recorded source, its contribution cannot be measured. Cap at 1 and report the tracking gap as the finding.'),
  ('7.3', '7.3-R2', 'client_document', null,
   null, null, 'Whether referral is a distinguishable source on opportunities',
   true, 'Where referral is not a recorded source, its contribution cannot be measured. Cap at 1 and report the tracking gap as the finding.'),
  ('7.4', '7.4-R1', 'export', array['T3-07','T3-03']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where no advocacy activity exists at all, that is a level 0 finding rather than NE.'),
  ('7.4', '7.4-R2', 'client_document', null,
   null, null, 'Any advocacy programme, advocate list and tiering',
   true, 'Where no advocacy activity exists at all, that is a level 0 finding rather than NE.'),
  ('7.4', '7.4-R3', 'public_surface', null,
   null, null, 'Content inventory of customer-led content',
   true, 'Where no advocacy activity exists at all, that is a level 0 finding rather than NE.'),
  ('7.5', '7.5-R1', 'export', array['T3-06']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where no satisfaction measurement runs at all, mark level 0 rather than NE.'),
  ('7.5', '7.5-R2', 'client_document', null,
   null, null, 'Survey instrument, cadence and response rate',
   true, 'Where no satisfaction measurement runs at all, mark level 0 rather than NE.'),
  ('7.5', '7.5-R3', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'Where no satisfaction measurement runs at all, mark level 0 rather than NE.'),
  ('H07', 'H07-R1', 'export', array['T3-06','T1-01']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply.'),
  ('H07', 'H07-R2', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'Both sides of a handoff are always available for interview, so NE does not apply.'),
  ('8.1', '8.1-R1', 'export', array['T1-02','T1-04','T1-07']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Ownership data is always retrievable in some form, so NE does not apply. Where it sits outside the CRM, note where it sits as a finding.'),
  ('8.1', '8.1-R2', 'client_document', null,
   null, null, 'Product or service ownership per account from the system of record',
   true, 'Ownership data is always retrievable in some form, so NE does not apply. Where it sits outside the CRM, note where it sits as a finding.'),
  ('8.1', '8.1-R3', 'interview', null,
   4, null, 'Accepted synthesis from the Revenue operations session',
   true, 'Ownership data is always retrievable in some form, so NE does not apply. Where it sits outside the CRM, note where it sits as a finding.'),
  ('8.2', '8.2-R1', 'export', array['T1-01','T1-04','T3-05']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where expansion events cannot be distinguished from new business in the record, reconstruct from contract or invoice data, state the method, and cap confidence at Medium.'),
  ('8.2', '8.2-R2', 'analysis', null,
   null, 'expansion_vs_new_business', 'Accepted run of the expansion vs new business analysis',
   true, 'Where expansion events cannot be distinguished from new business in the record, reconstruct from contract or invoice data, state the method, and cap confidence at Medium.'),
  ('8.2', '8.2-R3', 'interview', null,
   4, null, 'Accepted synthesis from the Revenue operations session',
   true, 'Where expansion events cannot be distinguished from new business in the record, reconstruct from contract or invoice data, state the method, and cap confidence at Medium.'),
  ('8.3', '8.3-R1', 'export', array['T1-01','T1-04']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where expansion path is not recorded, derive it from product ownership before and after, state the method, and cap confidence at Medium.'),
  ('8.3', '8.3-R2', 'analysis', null,
   null, 'expansion_vs_new_business', 'Accepted run of the expansion vs new business analysis',
   true, 'Where expansion path is not recorded, derive it from product ownership before and after, state the method, and cap confidence at Medium.'),
  ('8.3', '8.3-R3', 'client_document', null,
   null, null, 'All expansion-specific material and how it is differentiated by segment and current ownership',
   true, 'Where expansion path is not recorded, derive it from product ownership before and after, state the method, and cap confidence at Medium.'),
  ('8.3', '8.3-R4', 'interview', null,
   3, null, 'Accepted synthesis from the Sales leadership session',
   true, 'Where expansion path is not recorded, derive it from product ownership before and after, state the method, and cap confidence at Medium.'),
  ('8.4', '8.4-R1', 'export', array['T1-07','T1-01']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where gross and net retention are conflated in reporting, compute both from the raw records and report the conflation as a finding.'),
  ('8.4', '8.4-R2', 'analysis', null,
   null, 'renewal_timing_and_reason', 'Accepted run of the renewal timing and reason analysis',
   true, 'Where gross and net retention are conflated in reporting, compute both from the raw records and report the conflation as a finding.'),
  ('8.4', '8.4-R3', 'client_document', null,
   null, null, 'Renewal process documentation and its defined start point',
   true, 'Where gross and net retention are conflated in reporting, compute both from the raw records and report the conflation as a finding.'),
  ('8.4', '8.4-R4', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'Where gross and net retention are conflated in reporting, compute both from the raw records and report the conflation as a finding.'),
  ('8.4', '8.4-R5', 'interview', null,
   6, null, 'Accepted synthesis from the Finance session',
   true, 'Where gross and net retention are conflated in reporting, compute both from the raw records and report the conflation as a finding.'),
  ('8.5', '8.5-R1', 'export', array['T3-10']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Where no account plans exist, mark level 0 rather than NE.'),
  ('8.5', '8.5-R2', 'client_document', null,
   null, null, 'Account plans for the priority accounts with authorship and revision dates',
   true, 'Where no account plans exist, mark level 0 rather than NE.'),
  ('8.5', '8.5-R3', 'interview', null,
   5, null, 'Accepted synthesis from the Customer success session',
   true, 'Where no account plans exist, mark level 0 rather than NE.'),
  ('H08', 'H08-R1', 'export', array['T1-01','T1-07']::text[],
   null, null, 'Client system export covering this element''s population',
   true, 'Read this handoff alongside the ICP Reconciliation result. A high variance rate with a level 4 or 5 score here is a contradiction: re-check both before publishing.'),
  ('H08', 'H08-R2', 'client_document', null,
   null, null, 'Whether renewal, churn and expansion outcomes reach ICP and segment review, on what schedule, and whether predictors are identified rather than outcomes alone',
   true, 'Read this handoff alongside the ICP Reconciliation result. A high variance rate with a level 4 or 5 score here is a contradiction: re-check both before publishing.'),
  ('H08', 'H08-R3', 'interview', null,
   1, null, 'Accepted synthesis from the Executive sponsor session',
   true, 'Read this handoff alongside the ICP Reconciliation result. A high variance rate with a level 4 or 5 score here is a contradiction: re-check both before publishing.')
) as v(element_ref, ref, source_kind, export_line_refs, guide_ref,
       analysis_key, description, is_mandatory, waiver_consequence)
join element e on e.ref = v.element_ref and e.instrument_version_id = '0f6a0006-0000-4000-8000-000000000006'
left join interview_guide g on g.ref = v.guide_ref and g.instrument_version_id = '0f6a0006-0000-4000-8000-000000000006';
